%%-*-erlang-*-
{add_view,[{path,[]},{perms,["admin"]},{view,"spreadsheet"}]}.
{add_view,[{path,[]},{perms,["admin"]},{view,"table"}]}.
{add_view,[{path,[]},{perms,["admin",everyone]},{view,"webpage"}]}.
{set_champion,[{path,[]},{view,"webpage"}]}.
{add_view,[{path,["replies"]},{perms,["admin"]},{view,"spreadsheet"}]}.
{add_view,[{path,["replies"]},{perms,["admin", everyone]},{view,"table"}]}.
{add_view,[{path,["replies"]},{perms,["admin"]},{view,"webpage"}]}.
{set_champion,[{path,["replies"]},{view,"table"}]}.
