{application, remoting,
	[{description,  "The remoting application"},
	 {vsn,          "1.0"},
	 {modules,      [remoting_reg,
			 remoting_srv,
			 remoting_sup,
			 socket,
			 remoting]},
	 {registered,   [ ]},
	 {included_applications, []},
	 {applications, [kernel, stdlib]},
	 {mod,		{remoting, [ ]}}]}.
