% This module has been generated by generatetest.rb
% DO NOT EDIT MANUALLY.
%
% Source file: basic_unicode_strings.xls
% Generated on: Sat Jan 26 01:08:46 +0000 2008

-module(basic_unicode_strings_SUITE).
-compile(export_all).
-include("ct.hrl").


init_per_suite(Config) ->
    code:add_patha("../../../../../ebin"),
    production_boot:setup_paths(),
    Data = test_util:read_excel_file("/Win Excel 2007 (as 97)/basic_unicode_strings.xls"),
    %% io:format("in init_per_suite Data is ~p~n",[Data]),
    lists:merge([Config, [{basic_unicode_strings_SUITE, Data}]]).
  
end_per_suite(_Config) ->
    ok.
  
init_per_testcase(_TestCase, Config) -> Config.

end_per_testcase(_TestCase, _Config) -> ok.

read_from_excel_data(Config, {Row,Col}) ->
    {value, Result} = lists:keysearch(basic_unicode_strings_SUITE, 1, Config),
    Data = element(2, Result),
    Key={{row_index,Row},{col_index,Col}},
    {value, Result2} = lists:keysearch(Key, 1, Data),
    El=element(2, Result2),
    %% io:format("El is ~p~n",[El]),
    case El of
        {value, number, Number} -> {number,Number};
        {string,String}         -> {string,String};
        {formula,Formula}       -> {formula,Formula};
        {value,boolean,Boolean} -> {boolean,Boolean};
        {value,error,Error}     -> {error, Error};
        Other                   -> io:format("(in generatetest.rb - fix me Other is ~p~n",[Other])
    end.

a5_test(doc) -> [{userdata,[{""}]}];
a5_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"From the Word Insert Special Character dialog box"},read_from_excel_data(Config,{4,0})]),
  test_util:expected2(read_from_excel_data(Config,{4,0}), {string,"From the Word Insert Special Character dialog box"}).
  
a16_test(doc) -> [{userdata,[{""}]}];
a16_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Currency Symbols"},read_from_excel_data(Config,{15,0})]),
  test_util:expected2(read_from_excel_data(Config,{15,0}), {string,"Currency Symbols"}).
  
a27_test(doc) -> [{userdata,[{""}]}];
a27_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Latin1 Supplement"},read_from_excel_data(Config,{26,0})]),
  test_util:expected2(read_from_excel_data(Config,{26,0}), {string,"Latin1 Supplement"}).
  
a38_test(doc) -> [{userdata,[{""}]}];
a38_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Letterlike Symbols"},read_from_excel_data(Config,{37,0})]),
  test_util:expected2(read_from_excel_data(Config,{37,0}), {string,"Letterlike Symbols"}).
  
a11_test(doc) -> [{userdata,[{""}]}];
a11_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Greek And Coptic"},read_from_excel_data(Config,{10,0})]),
  test_util:expected2(read_from_excel_data(Config,{10,0}), {string,"Greek And Coptic"}).
  
a22_test(doc) -> [{userdata,[{""}]}];
a22_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Alphabetic Presentation Forms"},read_from_excel_data(Config,{21,0})]),
  test_util:expected2(read_from_excel_data(Config,{21,0}), {string,"Alphabetic Presentation Forms"}).
  
a33_test(doc) -> [{userdata,[{""}]}];
a33_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Cyrillic"},read_from_excel_data(Config,{32,0})]),
  test_util:expected2(read_from_excel_data(Config,{32,0}), {string,"Cyrillic"}).
  
a6_test(doc) -> [{userdata,[{""}]}];
a6_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Latin1 Supplement"},read_from_excel_data(Config,{5,0})]),
  test_util:expected2(read_from_excel_data(Config,{5,0}), {string,"Latin1 Supplement"}).
  
a17_test(doc) -> [{userdata,[{""}]}];
a17_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Letterlike Symbols"},read_from_excel_data(Config,{16,0})]),
  test_util:expected2(read_from_excel_data(Config,{16,0}), {string,"Letterlike Symbols"}).
  
a28_test(doc) -> [{userdata,[{""}]}];
a28_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Latin Extended A"},read_from_excel_data(Config,{27,0})]),
  test_util:expected2(read_from_excel_data(Config,{27,0}), {string,"Latin Extended A"}).
  
a39_test(doc) -> [{userdata,[{""}]}];
a39_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Number Forms"},read_from_excel_data(Config,{38,0})]),
  test_util:expected2(read_from_excel_data(Config,{38,0}), {string,"Number Forms"}).
  
a1_test(doc) -> [{userdata,[{""}]}];
a1_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"This just tests some Unicode strings"},read_from_excel_data(Config,{0,0})]),
  test_util:expected2(read_from_excel_data(Config,{0,0}), {string,"This just tests some Unicode strings"}).
  
a12_test(doc) -> [{userdata,[{""}]}];
a12_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Cyrillic"},read_from_excel_data(Config,{11,0})]),
  test_util:expected2(read_from_excel_data(Config,{11,0}), {string,"Cyrillic"}).
  
a34_test(doc) -> [{userdata,[{""}]}];
a34_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Latin Extended Additional"},read_from_excel_data(Config,{33,0})]),
  test_util:expected2(read_from_excel_data(Config,{33,0}), {string,"Latin Extended Additional"}).
  
a7_test(doc) -> [{userdata,[{""}]}];
a7_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Latin Extended A"},read_from_excel_data(Config,{6,0})]),
  test_util:expected2(read_from_excel_data(Config,{6,0}), {string,"Latin Extended A"}).
  
a18_test(doc) -> [{userdata,[{""}]}];
a18_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Number Forms"},read_from_excel_data(Config,{17,0})]),
  test_util:expected2(read_from_excel_data(Config,{17,0}), {string,"Number Forms"}).
  
a29_test(doc) -> [{userdata,[{""}]}];
a29_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Latin Extended B"},read_from_excel_data(Config,{28,0})]),
  test_util:expected2(read_from_excel_data(Config,{28,0}), {string,"Latin Extended B"}).
  
a40_test(doc) -> [{userdata,[{""}]}];
a40_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Arrows"},read_from_excel_data(Config,{39,0})]),
  test_util:expected2(read_from_excel_data(Config,{39,0}), {string,"Arrows"}).
  
a2_test(doc) -> [{userdata,[{""}]}];
a2_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Some simple stuff"},read_from_excel_data(Config,{1,0})]),
  test_util:expected2(read_from_excel_data(Config,{1,0}), {string,"Some simple stuff"}).
  
a13_test(doc) -> [{userdata,[{""}]}];
a13_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Latin Extended Additional"},read_from_excel_data(Config,{12,0})]),
  test_util:expected2(read_from_excel_data(Config,{12,0}), {string,"Latin Extended Additional"}).
  
a24_test(doc) -> [{userdata,[{""}]}];
a24_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"The above in a function"},read_from_excel_data(Config,{23,0})]),
  test_util:expected2(read_from_excel_data(Config,{23,0}), {string,"The above in a function"}).
  
a35_test(doc) -> [{userdata,[{""}]}];
a35_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"General Punctuation"},read_from_excel_data(Config,{34,0})]),
  test_util:expected2(read_from_excel_data(Config,{34,0}), {string,"General Punctuation"}).
  
a8_test(doc) -> [{userdata,[{""}]}];
a8_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Latin Extended B"},read_from_excel_data(Config,{7,0})]),
  test_util:expected2(read_from_excel_data(Config,{7,0}), {string,"Latin Extended B"}).
  
a19_test(doc) -> [{userdata,[{""}]}];
a19_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Arrows"},read_from_excel_data(Config,{18,0})]),
  test_util:expected2(read_from_excel_data(Config,{18,0}), {string,"Arrows"}).
  
a30_test(doc) -> [{userdata,[{""}]}];
a30_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Spacing Modifying Letters"},read_from_excel_data(Config,{29,0})]),
  test_util:expected2(read_from_excel_data(Config,{29,0}), {string,"Spacing Modifying Letters"}).
  
a41_test(doc) -> [{userdata,[{""}]}];
a41_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Mathematical Operators"},read_from_excel_data(Config,{40,0})]),
  test_util:expected2(read_from_excel_data(Config,{40,0}), {string,"Mathematical Operators"}).
  
a14_test(doc) -> [{userdata,[{""}]}];
a14_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"General Punctuation"},read_from_excel_data(Config,{13,0})]),
  test_util:expected2(read_from_excel_data(Config,{13,0}), {string,"General Punctuation"}).
  
a25_test(doc) -> [{userdata,[{""}]}];
a25_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Some simple stuff"},read_from_excel_data(Config,{24,0})]),
  test_util:expected2(read_from_excel_data(Config,{24,0}), {string,"Some simple stuff"}).
  
a36_test(doc) -> [{userdata,[{""}]}];
a36_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Superscripts and Subscripts"},read_from_excel_data(Config,{35,0})]),
  test_util:expected2(read_from_excel_data(Config,{35,0}), {string,"Superscripts and Subscripts"}).
  
a9_test(doc) -> [{userdata,[{""}]}];
a9_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Spacing Modifying Letters"},read_from_excel_data(Config,{8,0})]),
  test_util:expected2(read_from_excel_data(Config,{8,0}), {string,"Spacing Modifying Letters"}).
  
a20_test(doc) -> [{userdata,[{""}]}];
a20_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Mathematical Operators"},read_from_excel_data(Config,{19,0})]),
  test_util:expected2(read_from_excel_data(Config,{19,0}), {string,"Mathematical Operators"}).
  
a31_test(doc) -> [{userdata,[{""}]}];
a31_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Combining Diacritical Marks"},read_from_excel_data(Config,{30,0})]),
  test_util:expected2(read_from_excel_data(Config,{30,0}), {string,"Combining Diacritical Marks"}).
  
a42_test(doc) -> [{userdata,[{""}]}];
a42_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Geometric Shapes"},read_from_excel_data(Config,{41,0})]),
  test_util:expected2(read_from_excel_data(Config,{41,0}), {string,"Geometric Shapes"}).
  
a15_test(doc) -> [{userdata,[{""}]}];
a15_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Superscripts and Subscripts"},read_from_excel_data(Config,{14,0})]),
  test_util:expected2(read_from_excel_data(Config,{14,0}), {string,"Superscripts and Subscripts"}).
  
a37_test(doc) -> [{userdata,[{""}]}];
a37_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Currency Symbols"},read_from_excel_data(Config,{36,0})]),
  test_util:expected2(read_from_excel_data(Config,{36,0}), {string,"Currency Symbols"}).
  
a10_test(doc) -> [{userdata,[{""}]}];
a10_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Combining Diacritical Marks"},read_from_excel_data(Config,{9,0})]),
  test_util:expected2(read_from_excel_data(Config,{9,0}), {string,"Combining Diacritical Marks"}).
  
a21_test(doc) -> [{userdata,[{""}]}];
a21_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Geometric Shapes"},read_from_excel_data(Config,{20,0})]),
  test_util:expected2(read_from_excel_data(Config,{20,0}), {string,"Geometric Shapes"}).
  
a32_test(doc) -> [{userdata,[{""}]}];
a32_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Greek And Coptic"},read_from_excel_data(Config,{31,0})]),
  test_util:expected2(read_from_excel_data(Config,{31,0}), {string,"Greek And Coptic"}).
  
a43_test(doc) -> [{userdata,[{""}]}];
a43_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Alphabetic Presentation Forms"},read_from_excel_data(Config,{42,0})]),
  test_util:expected2(read_from_excel_data(Config,{42,0}), {string,"Alphabetic Presentation Forms"}).
  
b16_test(doc) -> [{userdata,[{""}]}];
b16_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"€"},read_from_excel_data(Config,{15,1})]),
  test_util:expected2(read_from_excel_data(Config,{15,1}), {string,"€"}).
  
b27_test(doc) -> [{userdata,[{""}]}];
b27_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"áâãäåæ\")"},read_from_excel_data(Config,{26,1})]),
  test_util:expected2(read_from_excel_data(Config,{26,1}), {formula,"=CLEAN(\"áâãäåæ\")"}).
  
b38_test(doc) -> [{userdata,[{""}]}];
b38_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"l???™?\")"},read_from_excel_data(Config,{37,1})]),
  test_util:expected2(read_from_excel_data(Config,{37,1}), {formula,"=CLEAN(\"l???™?\")"}).
  
b11_test(doc) -> [{userdata,[{""}]}];
b11_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"??;???????G?"},read_from_excel_data(Config,{10,1})]),
  test_util:expected2(read_from_excel_data(Config,{10,1}), {string,"??;???????G?"}).
  
b22_test(doc) -> [{userdata,[{""}]}];
b22_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"?????"},read_from_excel_data(Config,{21,1})]),
  test_util:expected2(read_from_excel_data(Config,{21,1}), {string,"?????"}).
  
b33_test(doc) -> [{userdata,[{""}]}];
b33_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"???????\")"},read_from_excel_data(Config,{32,1})]),
  test_util:expected2(read_from_excel_data(Config,{32,1}), {formula,"=CLEAN(\"???????\")"}).
  
b6_test(doc) -> [{userdata,[{""}]}];
b6_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"áâãäåæ"},read_from_excel_data(Config,{5,1})]),
  test_util:expected2(read_from_excel_data(Config,{5,1}), {string,"áâãäåæ"}).
  
b17_test(doc) -> [{userdata,[{""}]}];
b17_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"l???™?"},read_from_excel_data(Config,{16,1})]),
  test_util:expected2(read_from_excel_data(Config,{16,1}), {string,"l???™?"}).
  
b28_test(doc) -> [{userdata,[{""}]}];
b28_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"AaAaAa\")"},read_from_excel_data(Config,{27,1})]),
  test_util:expected2(read_from_excel_data(Config,{27,1}), {formula,"=CLEAN(\"AaAaAa\")"}).
  
b39_test(doc) -> [{userdata,[{""}]}];
b39_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"??????\")"},read_from_excel_data(Config,{38,1})]),
  test_util:expected2(read_from_excel_data(Config,{38,1}), {formula,"=CLEAN(\"??????\")"}).
  
b12_test(doc) -> [{userdata,[{""}]}];
b12_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"???????"},read_from_excel_data(Config,{11,1})]),
  test_util:expected2(read_from_excel_data(Config,{11,1}), {string,"???????"}).
  
b34_test(doc) -> [{userdata,[{""}]}];
b34_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"????????\")"},read_from_excel_data(Config,{33,1})]),
  test_util:expected2(read_from_excel_data(Config,{33,1}), {formula,"=CLEAN(\"????????\")"}).
  
b7_test(doc) -> [{userdata,[{""}]}];
b7_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"AaAaAa"},read_from_excel_data(Config,{6,1})]),
  test_util:expected2(read_from_excel_data(Config,{6,1}), {string,"AaAaAa"}).
  
b18_test(doc) -> [{userdata,[{""}]}];
b18_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"??????"},read_from_excel_data(Config,{17,1})]),
  test_util:expected2(read_from_excel_data(Config,{17,1}), {string,"??????"}).
  
b29_test(doc) -> [{userdata,[{""}]}];
b29_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"ƒ?????\")"},read_from_excel_data(Config,{28,1})]),
  test_util:expected2(read_from_excel_data(Config,{28,1}), {formula,"=CLEAN(\"ƒ?????\")"}).
  
b40_test(doc) -> [{userdata,[{""}]}];
b40_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"??????????\")"},read_from_excel_data(Config,{39,1})]),
  test_util:expected2(read_from_excel_data(Config,{39,1}), {formula,"=CLEAN(\"??????????\")"}).
  
b2_test(doc) -> [{userdata,[{""}]}];
b2_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ß"},read_from_excel_data(Config,{1,1})]),
  test_util:expected2(read_from_excel_data(Config,{1,1}), {string,"ß"}).
  
b13_test(doc) -> [{userdata,[{""}]}];
b13_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"????????"},read_from_excel_data(Config,{12,1})]),
  test_util:expected2(read_from_excel_data(Config,{12,1}), {string,"????????"}).
  
b35_test(doc) -> [{userdata,[{""}]}];
b35_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"-–—?‘’‚\")"},read_from_excel_data(Config,{34,1})]),
  test_util:expected2(read_from_excel_data(Config,{34,1}), {formula,"=CLEAN(\"-–—?‘’‚\")"}).
  
b8_test(doc) -> [{userdata,[{""}]}];
b8_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ƒ?????"},read_from_excel_data(Config,{7,1})]),
  test_util:expected2(read_from_excel_data(Config,{7,1}), {string,"ƒ?????"}).
  
b19_test(doc) -> [{userdata,[{""}]}];
b19_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"??????????"},read_from_excel_data(Config,{18,1})]),
  test_util:expected2(read_from_excel_data(Config,{18,1}), {string,"??????????"}).
  
b30_test(doc) -> [{userdata,[{""}]}];
b30_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"aˆb?c?d¯e¯f?g?h?i?\")"},read_from_excel_data(Config,{29,1})]),
  test_util:expected2(read_from_excel_data(Config,{29,1}), {formula,"=CLEAN(\"aˆb?c?d¯e¯f?g?h?i?\")"}).
  
b41_test(doc) -> [{userdata,[{""}]}];
b41_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"????\")"},read_from_excel_data(Config,{40,1})]),
  test_util:expected2(read_from_excel_data(Config,{40,1}), {formula,"=CLEAN(\"????\")"}).
  
b3_test(doc) -> [{userdata,[{""}]}];
b3_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"kfdks45678dkßsfjk"},read_from_excel_data(Config,{2,1})]),
  test_util:expected2(read_from_excel_data(Config,{2,1}), {string,"kfdks45678dkßsfjk"}).
  
b14_test(doc) -> [{userdata,[{""}]}];
b14_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"-–—?‘’‚"},read_from_excel_data(Config,{13,1})]),
  test_util:expected2(read_from_excel_data(Config,{13,1}), {string,"-–—?‘’‚"}).
  
b25_test(doc) -> [{userdata,[{""}]}];
b25_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"ß\")"},read_from_excel_data(Config,{24,1})]),
  test_util:expected2(read_from_excel_data(Config,{24,1}), {formula,"=CLEAN(\"ß\")"}).
  
b36_test(doc) -> [{userdata,[{""}]}];
b36_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"°456789?????\")"},read_from_excel_data(Config,{35,1})]),
  test_util:expected2(read_from_excel_data(Config,{35,1}), {formula,"=CLEAN(\"°456789?????\")"}).
  
b9_test(doc) -> [{userdata,[{""}]}];
b9_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"aˆb?c?d¯e¯f?g?h?i?"},read_from_excel_data(Config,{8,1})]),
  test_util:expected2(read_from_excel_data(Config,{8,1}), {string,"aˆb?c?d¯e¯f?g?h?i?"}).
  
b20_test(doc) -> [{userdata,[{""}]}];
b20_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"????"},read_from_excel_data(Config,{19,1})]),
  test_util:expected2(read_from_excel_data(Config,{19,1}), {string,"????"}).
  
b31_test(doc) -> [{userdata,[{""}]}];
b31_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"a`b´c^d~¯e?f?¨°g?h?\")"},read_from_excel_data(Config,{30,1})]),
  test_util:expected2(read_from_excel_data(Config,{30,1}), {formula,"=CLEAN(\"a`b´c^d~¯e?f?¨°g?h?\")"}).
  
b42_test(doc) -> [{userdata,[{""}]}];
b42_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"?\")"},read_from_excel_data(Config,{41,1})]),
  test_util:expected2(read_from_excel_data(Config,{41,1}), {formula,"=CLEAN(\"?\")"}).
  
b15_test(doc) -> [{userdata,[{""}]}];
b15_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"°456789?????"},read_from_excel_data(Config,{14,1})]),
  test_util:expected2(read_from_excel_data(Config,{14,1}), {string,"°456789?????"}).
  
b26_test(doc) -> [{userdata,[{""}]}];
b26_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"kfdks45678dkßsfjk\")"},read_from_excel_data(Config,{25,1})]),
  test_util:expected2(read_from_excel_data(Config,{25,1}), {formula,"=CLEAN(\"kfdks45678dkßsfjk\")"}).
  
b37_test(doc) -> [{userdata,[{""}]}];
b37_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"€\")"},read_from_excel_data(Config,{36,1})]),
  test_util:expected2(read_from_excel_data(Config,{36,1}), {formula,"=CLEAN(\"€\")"}).
  
b10_test(doc) -> [{userdata,[{""}]}];
b10_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"a`b´c^d~¯e?f?¨°g?h?"},read_from_excel_data(Config,{9,1})]),
  test_util:expected2(read_from_excel_data(Config,{9,1}), {string,"a`b´c^d~¯e?f?¨°g?h?"}).
  
b21_test(doc) -> [{userdata,[{""}]}];
b21_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"?"},read_from_excel_data(Config,{20,1})]),
  test_util:expected2(read_from_excel_data(Config,{20,1}), {string,"?"}).
  
b32_test(doc) -> [{userdata,[{""}]}];
b32_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"??;???????G?\")"},read_from_excel_data(Config,{31,1})]),
  test_util:expected2(read_from_excel_data(Config,{31,1}), {formula,"=CLEAN(\"??;???????G?\")"}).
  
b43_test(doc) -> [{userdata,[{""}]}];
b43_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CLEAN(\"?????\")"},read_from_excel_data(Config,{42,1})]),
  test_util:expected2(read_from_excel_data(Config,{42,1}), {formula,"=CLEAN(\"?????\")"}).
  
all() -> 
    [a5_test,
   a16_test,
   a27_test,
   a38_test,
   a11_test,
   a22_test,
   a33_test,
   a6_test,
   a17_test,
   a28_test,
   a39_test,
   a1_test,
   a12_test,
   a34_test,
   a7_test,
   a18_test,
   a29_test,
   a40_test,
   a2_test,
   a13_test,
   a24_test,
   a35_test,
   a8_test,
   a19_test,
   a30_test,
   a41_test,
   a14_test,
   a25_test,
   a36_test,
   a9_test,
   a20_test,
   a31_test,
   a42_test,
   a15_test,
   a37_test,
   a10_test,
   a21_test,
   a32_test,
   a43_test,
   b16_test,
   b27_test,
   b38_test,
   b11_test,
   b22_test,
   b33_test,
   b6_test,
   b17_test,
   b28_test,
   b39_test,
   b12_test,
   b34_test,
   b7_test,
   b18_test,
   b29_test,
   b40_test,
   b2_test,
   b13_test,
   b35_test,
   b8_test,
   b19_test,
   b30_test,
   b41_test,
   b3_test,
   b14_test,
   b25_test,
   b36_test,
   b9_test,
   b20_test,
   b31_test,
   b42_test,
   b15_test,
   b26_test,
   b37_test,
   b10_test,
   b21_test,
   b32_test,
   b43_test
    ].
  
