#!/bin/sh

# Pass any parameter to this script for quick compile (only recompile the main 
# app), e.g.: ./compile_code quick
cd `dirname $0`

if [ ! -n "$1" ] 
then

    echo "==============================="
    echo "      COMPILING STARLING      "
    echo "==============================="
    cd ./lib/starling/
    rake
    cd ../../
    echo "OK"

    echo "==============================="
    echo " GENERATING LEXERS AND PARSERS "
    echo "==============================="
    cd ./priv/muin/
    erlc generate.erl
    erl -noshell -s generate gen -s init stop
    cd ../../
    echo "OK"
fi

echo
echo "==============================="
echo "       COMPILING COMPILER      "
echo "==============================="
erlc -o ebin src/compile_code.erl

echo
echo "==============================="
echo "      GENERATING MS_UTIL       "
echo "==============================="
erlc -o ebin -I include priv/ms_util/make_ms_util.erl
# GG 2008_09_02
# for the life of me I can't get epp:parse_file to take a path
# so I cd to where spriki.hrl is
# (shoddy, can't get the staff!)
cd ./include
erl -pa ../ebin -noshell -s make_ms_util make -s init stop
mv ms_util2.erl ../lib/hypernumbers-1.0/src
cd ../
echo
echo "==============================="
echo "            BUILDING           "
echo "==============================="
cd ebin
erl -pa ebin -noshell -s compile_code -s init stop
