#!/bin/sh

# Pass any parameter to this script for quick compile (only recompile the main 
# app), e.g.: ./compile_code quick
cd `dirname $0`

if [ ! -n "$1" ] 
then
    echo "=================="
    echo "COMPILING STARLING"
    echo "=================="
    cd ./lib/starling/
    rake
    cd ../../
    echo "OK"

    echo "============================="
    echo "GENERATING LEXERS AND PARSERS"
    echo "============================="
    cd ./priv/muin/
    erlc generate.erl
    erl -noshell -s generate gen -s init stop
    cd ../../
    echo "OK"
fi

erlc -o ebin src/compile_code.erl

echo
echo "================"
echo "    BUILDING    "
echo "================"
cd ebin
erl -pa ebin -noshell -s compile_code -s init stop
