#!/bin/sh

echo "============================="
echo "GENERATING LEXERS AND PARSERS"
echo "============================="
# Generate lexers and parsers.
cd ./priv/muin/
erlc generate.erl
erl -noshell -s generate gen -s init stop
cd ../../

echo
echo "======================"
echo "COMPILING BUILD SCRIPT"
echo "======================"
erlc -o ebin src/compile_code.erl

echo
echo "================"
echo "    BUILDING    "
echo "================"
cd ebin
erl -pa ebin -noshell -s compile_code -s init stop
