#! /bin/bash

NODE=arrian
HOST=localhost
RELNAME=hypernumbers
SASL_CONF_FILE=sasl_dev_conf.config
COOKIE=abc
# If anything is broken, probably here
# this is the full path to the hypernumbers root dir, 
# readlink might need installed 
# if it breaks, can replace with 
# (/home/dale/hypernumbers) temporarily
# check if we are running under cywgin
OS_PLATFORM=`uname -a | cut -f 1 -d " "`
if [ $OS_PLATFORM = "CYGWIN_NT-6.0" ]
then
    TMP=`pwd`
    ROOT="c:/"`echo $TMP | cut -d "/" -f 4-`
elif [ $OS_PLATFORM = "Darwin" ]
then
    ROOT=`dirname $0`
else
    ROOT=$(dirname `readlink -f "$0"`)
fi

cd $ROOT

LOG_DIR=$ROOT/logs
CONFIG=$ROOT/priv/hypernumbers.conf
MNESIA_DIR=$ROOT/database/$NODE
REL_DIR=$ROOT/ebin/$RELNAME
SASL_DIR=$ROOT/priv/$SASL_CONF_FILE

HN_DIR="lib/hypernumbers-1.0"
MOCHI_DIR="lib/mochiweb"
GETTEXT_DIR="lib/gettext"
SGTE_DIR="lib/sgte"

## Create mnesia and log directories
## and config file if they dont exist
[ -d $LOG_DIR ]        || mkdir -p $LOG_DIR
[ -d $LOG_DIR/error ]  || mkdir -p $LOG_DIR/error
[ -d $MNESIA_DIR ]     || mkdir -p $MNESIA_DIR
[ -f $CONFIG ]         || cp $ROOT/priv/hypernumbers.conf.default $CONFIG

function build
{
    if [ $# -lt 1 ] 
    then
        echo "==============================="
        echo "      Compiling DEPTS          "
        echo "==============================="
        cd ./lib/mochiweb/
        make
        cd ../../
        cd ./lib/gettext/
        make
        cd ../../
        cd ./lib/sgte/
        % make
        cd ../../
        echo "==============================="
        echo "      Compiling Starling       "
        echo "==============================="
        cd ./lib/starling/
        rake
        cd ../../
        echo "==============================="
        echo " Generating Lexers And Parsers "
        echo "==============================="
        cd ./priv/muin/
        erlc generate.erl
        erl -noshell -s generate gen -s init stop
        cd ../../
    fi

    echo "==============================="
    echo "       Compiling Compiler      "
    echo "==============================="
    erlc -o ebin src/compile_code.erl
    echo "==============================="
    echo "      Generating ms_util       "
    echo "==============================="
    erlc -o $HN_DIR/ebin -I $HN_DIR/include priv/ms_util/make_ms_util.erl
    erl -pa $HN_DIR/ebin -noshell -s make_ms_util make -s init stop
    mv ms_util2.erl $HN_DIR/src
    echo "==============================="
    echo "            Compiling          "
    echo "==============================="
    cd ebin
    erl -pa ebin -noshell -s compile_code -s init stop
}

function start
{
    MODE="-detached"
    RELOAD=""

    if [ $# -lt 1 ] 
    then
        MODE=""
        RELOAD="-run reloader start"
    fi

    erl $MODE \
        $RELOAD \
        -setcookie $COOKIE \
        -sname $NODE@$HOST \
        -boot $REL_DIR \
        -config $SASL_DIR \
        -hn_config $CONFIG \
        -hn_log $LOG_DIR \
        -mnesia dir "\"$MNESIA_DIR\""       
}

function gen_tests
{
    erl -noshell \
        -setcookie $COOKIE \
        -sname $NODE@$HOST \
        -boot $REL_DIR \
        -config $SASL_DIR \
        -hn_config $CONFIG \
        -hn_log $LOG_DIR \
        -mnesia dir "\"$MNESIA_DIR\""\
        -pa ebin\
        -s generate_tests run \
        -s init stop
}

function docs
{
    echo "==============================="
    echo "     Building Documentation    "
    echo "==============================="
    HN_DIR="lib/hypernumbers-1.0"
    erlc -o ebin src/make_edoc.erl
    erl -pa ebin -noshell -s make_edoc build -s init stop
}

function gen_help
{
    echo "==============================="
    echo "     Building Help Files       "
    echo "==============================="
    erlc -o ebin -I $HN_DIR/include src/generate_help.erl
    erl -pa ebin -pa $HN_DIR/ebin -pa $MOCHI_DIR/ebin -s generate_help run -s init stop
}

function visualise
{
    cd ./priv/test_visualiser/
    ruby visualise_tests.rb
    cd ../../
}

function statsvn
{
    svn log -v --xml > ./logs/statsvn/svn.log
    cd ./logs/statsvn
    java -Xms512m -Xmx1024m -jar ../../priv/statsvn/statsvn.jar \
         ./svn.log ../../\
         -exclude tests/**:lib/eunit/**:lib/yaws-1.76/**:lib/mochi-1.0/**:**/*.java:**/*.jar:testroot/**
             
}

function test
{
    if [ $# -lt 1 ] 
    then
        echo "hypernumbers test 1a - to run specific test"
        echo "hypernumbers test 1  - to run specific X series"
        exit
    fi

    TESTS=$(find $ROOT/tests/ -maxdepth 1 -name "*$1*" \
        | grep -v .svn \
        | grep -v common_test-1.3.0 \
        | grep -v test_server-3.2.0 \
        | grep -v excel_files \
        | grep -v test_server-3.2.0)

    $ROOT/tests/common_test-1.3.0/priv/bin/run_test \
        -noshell \
        -setcookie $COOKIE \
        -sname $NODE-test@$HOST \
        -boot $REL_DIR \
        -config $SASL_DIR \
        -hn_config $CONFIG \
        -hn_log $LOG_DIR \
        -logdir $LOG_DIR \
        -mnesia dir "\"$MNESIA_DIR\"" \
        -dir $TESTS
}

function copylog
{
    HOST=alpha.hypernumbers.com
    NAME=hypernumbers
    PATH=alpha.hypernumbers.com
    /usr/bin/scp $NAME@$HOST:$PATH/lib/hypernumbers-1.0/log/post_log.LOG \
        lib/hypernumbers-1.0/log/test.LOG
}

function debug
{
    erl -sname debug@$HOST -setcookie $COOKIE -remsh $NODE@$HOST
}

function stop
{
    erl -detached \
        -sname $NODE-ctrl@$HOST \
        -setcookie $COOKIE \
        -eval "rpc:call($NODE@$HOST,init,stop,[])" \
        -s init stop
}

case $1 in 
    start)     start $2;;
    debug)     debug;;
    stop)      stop;;
    docs)      docs;;
    copylog)   copylog;;
    build)     build $2;;
    statsvn)   statsvn;;
    visualise) visualise;;
    gen_tests) gen_tests;;
    gen_help) gen_help;;
    test)      test $2;;
esac
