#! /bin/bash
./hn do hn_update:git_pull hypernumbers.com
./hn do hn_update:git_pull node2.hypernumbers.com
./hn do hn_update:git_pull node3.hypernumbers.com
./hn do hn_update:git_pull node4.hypernumbers.com
