# Generates builtins.hrl from stdfuns files.
# <hasan@hypernumbers.com>

files = ["stdfuns_stats.erl", "stdfuns_math.erl", "stdfuns_text.erl",
         "stdfuns_info.erl", "stdfuns_logical.erl", "stdfuns_financial.erl",
         "stdfuns_eng.erl"]

def get_export_list(file)
  ls = IO.readlines("../../lib/formula_engine-1.0/src/#{file}")

  first = 0
  last = 0

  0.upto(ls.length) do |i|
    first = i if ls[i] =~ /^\-export\(\[/
  end

  first.upto(ls.length) do |i|
    if ls[i] =~ /\]\)\./
      last = i
      break
    end
  end

  functions = ls.slice(first+1..last).reject { |l| 
    !(l =~ /\s*\%/).nil? # don't want commented lines
  }.map { |l|
    x = l.strip
    i = x.rindex("/") || 0
    x.slice(0...i) # don't want arities
  }.reject { |l|
    l == ""
  }

  functions
end

res = files.inject("") do |acc, name|
  mod = File.basename(name, ".erl")
  functions = get_export_list(name)
  acc += functions.map { |f| "{#{f}, #{mod}}" }.join(",\n") + ",\n"
end

res = "-define(STDFUNS, [\n" + res.slice!(0...-2) + "\n])."
res = "%%% Generated by gen_builtins.rb.\n" + res

File.open("builtins.hrl", "w") { |f| f << res }
