%% Lexer for German frontend for Muin.
%% Hasan Veldstra <hasan@hypernumbers.com>
%% Generated by generate_lexer.rb on Sun Apr 06 22:07:22 BST 2008

Definitions.

STRING    = (\"[^"\n]*\")
%" % Syntax highlighting fix.
WHITESPACE = ([\000-\s]*)

IPMT = (\132\111\116\123\132)
SMALL = (\113\113\114\105\111\116\123\124\105)
PI = (\120\111)
ISPMT = (\111\123\120\115\124)
STDEVPA = (\123\124\101\102\127\116\101)
MATCH = (\126\105\122\107\114\105\111\103\110)
HYPERLINK = (\110\131\120\105\122\114\111\116\113)
SECOND = (\123\105\113\125\116\104\105)
ISERROR = (\111\123\124\106\105\110\114\105\122)
ODD = (\125\116\107\105\122\101\104\105)
SKEW = (\123\103\110\111\105\106\105)
ISREF = (\111\123\124\102\105\132\125\107)
LOWER = (\113\114\105\111\116)
RIGHT = (\122\105\103\110\124\123)
VLOOKUP = (\123\126\105\122\127\105\111\123)
CODE = (\103\117\104\105)
SIN = (\123\111\116)
TRIMMEAN = (\107\105\123\124\125\124\132\124\115\111\124\124\105\114)
LOG10 = (\114\117\107\61\60)
HOUR = (\123\124\125\116\104\105)
DATE = (\104\101\124\125\115)
POISSON = (\120\117\111\123\123\117\116)
DDB = (\107\104\101)
CELL = (\132\105\114\114\105)
EXACT = (\111\104\105\116\124\111\123\103\110)
SQRT = (\127\125\122\132\105\114)
HLOOKUP = (\127\126\105\122\127\105\111\123)
ISLOGICAL = (\111\123\124\114\117\107)
FACT = (\106\101\113\125\114\124\303\204\124)
LOGEST = (\122\113\120)
DVAR = (\104\102\126\101\122\111\101\116\132)
RTD = (\122\124\104)
SLOPE = (\123\124\105\111\107\125\116\107)
LOGINV = (\114\117\107\111\116\126)
SLN = (\114\111\101)
BINOMDIST = (\102\111\116\117\115\126\105\122\124)
ROUNDUP = (\101\125\106\122\125\116\104\105\116)
ROUND = (\122\125\116\104\105\116)
ACOSH = (\101\122\103\103\117\123\110\131\120)
GAMMAINV = (\107\101\115\115\101\111\116\126)
COVAR = (\113\117\126\101\122)
FTEST = (\106\124\105\123\124)
IF = (\127\105\116\116)
DGET = (\104\102\101\125\123\132\125\107)
INDEX = (\111\116\104\105\130)
WEEKDAY = (\127\117\103\110\105\116\124\101\107)
GETPIVOTDATA = (\107\105\124\120\111\126\117\124\104\101\124\101)
SEARCH = (\123\125\103\110\105\116)
UNION = (\125\116\111\117\116)
NPV = (\116\102\127)
ATANH = (\101\122\103\124\101\116\110\131\120)
ISNONTEXT = (\111\123\124\113\124\105\130\124)
CHIINV = (\103\110\111\111\116\126)
SUMXMY2 = (\123\125\115\115\105\130\115\131\62)
TRIM = (\107\114\303\204\124\124\105\116)
N = (\116)
ZTEST = (\107\124\105\123\124)
VALUE = (\127\105\122\124)
BETADIST = (\102\105\124\101\126\105\122\124)
PV = (\102\127)
TREND = (\124\122\105\116\104)
AVEDEV = (\115\111\124\124\105\114\101\102\127)
DSTDEV = (\104\102\123\124\104\101\102\127)
NORMSDIST = (\123\124\101\116\104\116\117\122\115\126\105\122\124)
YEAR = (\112\101\110\122)
ERROR.TYPE = (\106\105\110\114\105\122\56\124\131\120)
FIND = (\106\111\116\104\105\116)
DVARP = (\104\102\126\101\122\111\101\116\132\105\116)
SINH = (\123\111\116\110\131\120)
SUM = (\123\125\115\115\105)
COLUMNS = (\123\120\101\114\124\105\116)
RAND = (\132\125\106\101\114\114\123\132\101\110\114)
GROWTH = (\126\101\122\111\101\124\111\117\116)
GEOMEAN = (\107\105\117\115\111\124\124\105\114)
DMIN = (\104\102\115\111\116)
T = (\124)
ATAN = (\101\122\103\124\101\116)
INTERCEPT = (\101\103\110\123\105\116\101\102\123\103\110\116\111\124\124)
FIXED = (\106\105\123\124)
TRUE = (\127\101\110\122)
COMBIN = (\113\117\115\102\111\116\101\124\111\117\116\105\116)
DCOUNT = (\104\102\101\116\132\101\110\114)
FISHER = (\106\111\123\110\105\122)
REPT = (\127\111\105\104\105\122\110\117\114\105\116)
MODE = (\115\117\104\101\114\127\105\122\124)
CLEAN = (\123\303\204\125\102\105\122\116)
TDIST = (\124\126\105\122\124)
FV = (\132\127)
LN = (\114\116)
COUNTIF = (\132\303\204\110\114\105\116\127\105\116\116)
EXP = (\105\130\120)
DAY = (\124\101\107)
LOOKUP = (\126\105\122\127\105\111\123)
CEILING = (\117\102\105\122\107\122\105\116\132\105)
TTEST = (\124\124\105\123\124)
MONTH = (\115\117\116\101\124)
ADDRESS = (\101\104\122\105\123\123\105)
OFFSET = (\102\105\122\105\111\103\110\56\126\105\122\123\103\110\111\105\102\105\116)
TYPE = (\124\131\120)
RANK = (\122\101\116\107)
LOGNORMDIST = (\114\117\107\116\117\122\115\126\105\122\124)
CORREL = (\113\117\122\122\105\114)
CHIDIST = (\103\110\111\126\105\122\124)
COSH = (\103\117\123\110\131\120)
PROB = (\127\101\110\122\123\103\110\102\105\122\105\111\103\110)
CHITEST = (\103\110\111\124\105\123\124)
RATE = (\132\111\116\123)
RADIANS = (\122\101\104\111\101\116\124)
INFO = (\111\116\106\117)
MINUTE = (\115\111\116\125\124\105)
WEIBULL = (\127\105\111\102\125\114\114)
AREAS = (\102\105\122\105\111\103\110\105)
ASIN = (\101\122\103\123\111\116)
NEGBINOMDIST = (\116\105\107\102\111\116\117\115\126\105\122\124)
MEDIAN = (\115\105\104\111\101\116)
MMULT = (\115\115\125\114\124)
TANH = (\124\101\116\110\131\120)
PRODUCT = (\120\122\117\104\125\113\124)
REPLACE = (\105\122\123\105\124\132\105\116)
BETAINV = (\102\105\124\101\111\116\126)
HYPGEOMDIST = (\110\131\120\107\105\117\115\126\105\122\124)
OR = (\117\104\105\122)
ISNA = (\111\123\124\116\126)
AVERAGEA = (\115\111\124\124\105\114\127\105\122\124\101)
NOT = (\116\111\103\110\124)
PERCENTILE = (\121\125\101\116\124\111\114)
ISERR = (\111\123\124\106\105\110\114)
ROMAN = (\122\303\226\115\111\123\103\110)
PEARSON = (\120\105\101\122\123\117\116)
CONFIDENCE = (\113\117\116\106\111\104\105\116\132)
VDB = (\126\104\102)
NOW = (\112\105\124\132\124)
COS = (\103\117\123)
NA = (\116\126)
VARA = (\126\101\122\111\101\116\132\101)
UPPER = (\107\122\117\123\123)
FORECAST = (\123\103\110\303\204\124\132\105\122)
FINV = (\106\111\116\126)
TINV = (\124\111\116\126)
PERCENTRANK = (\121\125\101\116\124\111\114\123\122\101\116\107)
FREQUENCY = (\110\303\204\125\106\111\107\113\105\111\124)
SIGN = (\126\117\122\132\105\111\103\110\105\116)
POWER = (\120\117\124\105\116\132)
DCOUNTA = (\104\102\101\116\132\101\110\114\62)
HARMEAN = (\110\101\122\115\111\124\124\105\114)
PROPER = (\107\122\117\123\123\62)
LOG = (\114\117\107)
FISHERINV = (\106\111\123\110\105\122\111\116\126)
STDEVA = (\123\124\101\102\127\101)
MAX = (\115\101\130)
LARGE = (\113\107\122\303\226\123\123\124\105)
DSTDEVP = (\104\102\123\124\104\101\102\127\116)
INDIRECT = (\111\116\104\111\122\105\113\124)
MDETERM = (\115\104\105\124)
PPMT = (\113\101\120\132)
TIME = (\132\105\111\124)
NORMINV = (\116\117\122\115\111\116\126)
RSQ = (\102\105\123\124\111\115\115\124\110\105\111\124\123\115\101\123\123)
DPRODUCT = (\104\102\120\122\117\104\125\113\124)
ISNUMBER = (\111\123\124\132\101\110\114)
TODAY = (\110\105\125\124\105)
DAYS360 = (\124\101\107\105\63\66\60)
CONCATENATE = (\126\105\122\113\105\124\124\105\116)
NPER = (\132\132\122)
LINEST = (\122\107\120)
CRITBINOM = (\113\122\111\124\102\111\116\117\115)
FDIST = (\106\126\105\122\124)
FLOOR = (\125\116\124\105\122\107\122\105\116\132\105)
DB = (\107\104\101\62)
COUNTBLANK = (\101\116\132\101\110\114\114\105\105\122\105\132\105\114\114\105\116)
DSUM = (\104\102\123\125\115\115\105)
ASINH = (\101\122\103\123\111\116\110\131\120)
CHAR = (\132\105\111\103\110\105\116)
KURT = (\113\125\122\124)
STDEV = (\123\124\101\102\127)
ROWS = (\132\105\111\114\105\116)
SUMPRODUCT = (\123\125\115\115\105\116\120\122\117\104\125\113\124)
VAR = (\126\101\122\111\101\116\132)
DATEVALUE = (\104\101\124\127\105\122\124)
IRR = (\111\113\126)
CHOOSE = (\127\101\110\114)
TIMEVALUE = (\132\105\111\124\127\105\122\124)
PERMUT = (\126\101\122\111\101\124\111\117\116\105\116)
DEGREES = (\107\122\101\104)
COUNT = (\101\116\132\101\110\114)
MINVERSE = (\115\111\116\126)
MID = (\124\105\111\114)
ISTEXT = (\111\123\124\124\105\130\124)
VARP = (\126\101\122\111\101\116\132\105\116)
STANDARDIZE = (\123\124\101\116\104\101\122\104\111\123\111\105\122\125\116\107)
LEFT = (\114\111\116\113\123)
ROUNDDOWN = (\101\102\122\125\116\104\105\116)
COUNTA = (\101\116\132\101\110\114\62)
AVERAGE = (\115\111\124\124\105\114\127\105\122\124)
STDEVP = (\123\124\101\102\127\116)
COLUMN = (\123\120\101\114\124\105)
SUMIF = (\123\125\115\115\105\127\105\116\116)
STEYX = (\123\124\106\105\110\114\105\122\131\130)
LEN = (\114\303\204\116\107\105)
GAMMALN = (\107\101\115\115\101\114\116)
SUMX2MY2 = (\123\125\115\115\105\130\62\115\131\62)
PMT = (\122\115\132)
FALSE = (\106\101\114\123\103\110)
INTERSECT = (\111\116\124\105\122\123\105\103\124)
GAMMADIST = (\107\101\115\115\101\126\105\122\124)
SUMSQ = (\121\125\101\104\122\101\124\105\123\125\115\115\105)
EVEN = (\107\105\122\101\104\105)
ATAN2 = (\101\122\103\124\101\116\62)
EXPONDIST = (\105\130\120\117\116\126\105\122\124)
TRANSPOSE = (\115\124\122\101\116\123)
VARPA = (\126\101\122\111\101\116\132\105\116\101)
ABS = (\101\102\123)
AND = (\125\116\104)
ISBLANK = (\111\123\124\114\105\105\122)
MOD = (\122\105\123\124)
SUBSTITUTE = (\127\105\103\110\123\105\114\116)
SYD = (\104\111\101)
ACOS = (\101\122\103\103\117\123)
NORMSINV = (\123\124\101\116\104\116\117\122\115\111\116\126)
SUMX2PY2 = (\123\125\115\115\105\130\62\120\131\62)
SUBTOTAL = (\124\105\111\114\105\122\107\105\102\116\111\123)
NORMDIST = (\116\117\122\115\126\105\122\124)
MIN = (\115\111\116)
DAVERAGE = (\104\102\115\111\124\124\105\114\127\105\122\124)
TEXT = (\124\105\130\124)
TAN = (\124\101\116)
ROW = (\132\105\111\114\105)
MAXA = (\115\101\130\101)
MINA = (\115\111\116\101)
DOLLAR = (\104\115)
MIRR = (\121\111\113\126)
TRUNC = (\113\303\234\122\132\105\116)
DMAX = (\104\102\115\101\130)
QUARTILE = (\121\125\101\122\124\111\114\105)
DEVSQ = (\123\125\115\121\125\101\104\101\102\127)
INT = (\107\101\116\132\132\101\110\114)


Rules.

% Preserve strings as-is.
{STRING} : {token, {string, YYtext}}.
% Kill whitespace.
{WHITESPACE} : .

{IPMT} : {token, {func, "ipmt"}}.
{SMALL} : {token, {func, "small"}}.
{PI} : {token, {func, "pi"}}.
{ISPMT} : {token, {func, "ispmt"}}.
{STDEVPA} : {token, {func, "stdevpa"}}.
{MATCH} : {token, {func, "match"}}.
{HYPERLINK} : {token, {func, "hyperlink"}}.
{SECOND} : {token, {func, "second"}}.
{ISERROR} : {token, {func, "iserror"}}.
{ODD} : {token, {func, "odd"}}.
{SKEW} : {token, {func, "skew"}}.
{ISREF} : {token, {func, "isref"}}.
{LOWER} : {token, {func, "lower"}}.
{RIGHT} : {token, {func, "right"}}.
{VLOOKUP} : {token, {func, "vlookup"}}.
{CODE} : {token, {func, "code"}}.
{SIN} : {token, {func, "sin"}}.
{TRIMMEAN} : {token, {func, "trimmean"}}.
{LOG10} : {token, {func, "log10"}}.
{HOUR} : {token, {func, "hour"}}.
{DATE} : {token, {func, "date"}}.
{POISSON} : {token, {func, "poisson"}}.
{DDB} : {token, {func, "ddb"}}.
{CELL} : {token, {func, "cell"}}.
{EXACT} : {token, {func, "exact"}}.
{SQRT} : {token, {func, "sqrt"}}.
{HLOOKUP} : {token, {func, "hlookup"}}.
{ISLOGICAL} : {token, {func, "islogical"}}.
{FACT} : {token, {func, "fact"}}.
{LOGEST} : {token, {func, "logest"}}.
{DVAR} : {token, {func, "dvar"}}.
{RTD} : {token, {func, "rtd"}}.
{SLOPE} : {token, {func, "slope"}}.
{LOGINV} : {token, {func, "loginv"}}.
{SLN} : {token, {func, "sln"}}.
{BINOMDIST} : {token, {func, "binomdist"}}.
{ROUNDUP} : {token, {func, "roundup"}}.
{ROUND} : {token, {func, "round"}}.
{ACOSH} : {token, {func, "acosh"}}.
{GAMMAINV} : {token, {func, "gammainv"}}.
{COVAR} : {token, {func, "covar"}}.
{FTEST} : {token, {func, "ftest"}}.
{IF} : {token, {func, "if"}}.
{DGET} : {token, {func, "dget"}}.
{INDEX} : {token, {func, "index"}}.
{WEEKDAY} : {token, {func, "weekday"}}.
{GETPIVOTDATA} : {token, {func, "getpivotdata"}}.
{SEARCH} : {token, {func, "search"}}.
{UNION} : {token, {func, "union"}}.
{NPV} : {token, {func, "npv"}}.
{ATANH} : {token, {func, "atanh"}}.
{ISNONTEXT} : {token, {func, "isnontext"}}.
{CHIINV} : {token, {func, "chiinv"}}.
{SUMXMY2} : {token, {func, "sumxmy2"}}.
{TRIM} : {token, {func, "trim"}}.
{N} : {token, {func, "n"}}.
{ZTEST} : {token, {func, "ztest"}}.
{VALUE} : {token, {func, "value"}}.
{BETADIST} : {token, {func, "betadist"}}.
{PV} : {token, {func, "pv"}}.
{TREND} : {token, {func, "trend"}}.
{AVEDEV} : {token, {func, "avedev"}}.
{DSTDEV} : {token, {func, "dstdev"}}.
{NORMSDIST} : {token, {func, "normsdist"}}.
{YEAR} : {token, {func, "year"}}.
{ERROR.TYPE} : {token, {func, "error.type"}}.
{FIND} : {token, {func, "find"}}.
{DVARP} : {token, {func, "dvarp"}}.
{SINH} : {token, {func, "sinh"}}.
{SUM} : {token, {func, "sum"}}.
{COLUMNS} : {token, {func, "columns"}}.
{RAND} : {token, {func, "rand"}}.
{GROWTH} : {token, {func, "growth"}}.
{GEOMEAN} : {token, {func, "geomean"}}.
{DMIN} : {token, {func, "dmin"}}.
{T} : {token, {func, "t"}}.
{ATAN} : {token, {func, "atan"}}.
{INTERCEPT} : {token, {func, "intercept"}}.
{FIXED} : {token, {func, "fixed"}}.
{TRUE} : {token, {func, "true"}}.
{COMBIN} : {token, {func, "combin"}}.
{DCOUNT} : {token, {func, "dcount"}}.
{FISHER} : {token, {func, "fisher"}}.
{REPT} : {token, {func, "rept"}}.
{MODE} : {token, {func, "mode"}}.
{CLEAN} : {token, {func, "clean"}}.
{TDIST} : {token, {func, "tdist"}}.
{FV} : {token, {func, "fv"}}.
{LN} : {token, {func, "ln"}}.
{COUNTIF} : {token, {func, "countif"}}.
{EXP} : {token, {func, "exp"}}.
{DAY} : {token, {func, "day"}}.
{LOOKUP} : {token, {func, "lookup"}}.
{CEILING} : {token, {func, "ceiling"}}.
{TTEST} : {token, {func, "ttest"}}.
{MONTH} : {token, {func, "month"}}.
{ADDRESS} : {token, {func, "address"}}.
{OFFSET} : {token, {func, "offset"}}.
{TYPE} : {token, {func, "type"}}.
{RANK} : {token, {func, "rank"}}.
{LOGNORMDIST} : {token, {func, "lognormdist"}}.
{CORREL} : {token, {func, "correl"}}.
{CHIDIST} : {token, {func, "chidist"}}.
{COSH} : {token, {func, "cosh"}}.
{PROB} : {token, {func, "prob"}}.
{CHITEST} : {token, {func, "chitest"}}.
{RATE} : {token, {func, "rate"}}.
{RADIANS} : {token, {func, "radians"}}.
{INFO} : {token, {func, "info"}}.
{MINUTE} : {token, {func, "minute"}}.
{WEIBULL} : {token, {func, "weibull"}}.
{AREAS} : {token, {func, "areas"}}.
{ASIN} : {token, {func, "asin"}}.
{NEGBINOMDIST} : {token, {func, "negbinomdist"}}.
{MEDIAN} : {token, {func, "median"}}.
{MMULT} : {token, {func, "mmult"}}.
{TANH} : {token, {func, "tanh"}}.
{PRODUCT} : {token, {func, "product"}}.
{REPLACE} : {token, {func, "replace"}}.
{BETAINV} : {token, {func, "betainv"}}.
{HYPGEOMDIST} : {token, {func, "hypgeomdist"}}.
{OR} : {token, {func, "or"}}.
{ISNA} : {token, {func, "isna"}}.
{AVERAGEA} : {token, {func, "averagea"}}.
{NOT} : {token, {func, "not"}}.
{PERCENTILE} : {token, {func, "percentile"}}.
{ISERR} : {token, {func, "iserr"}}.
{ROMAN} : {token, {func, "roman"}}.
{PEARSON} : {token, {func, "pearson"}}.
{CONFIDENCE} : {token, {func, "confidence"}}.
{VDB} : {token, {func, "vdb"}}.
{NOW} : {token, {func, "now"}}.
{COS} : {token, {func, "cos"}}.
{NA} : {token, {func, "na"}}.
{VARA} : {token, {func, "vara"}}.
{UPPER} : {token, {func, "upper"}}.
{FORECAST} : {token, {func, "forecast"}}.
{FINV} : {token, {func, "finv"}}.
{TINV} : {token, {func, "tinv"}}.
{PERCENTRANK} : {token, {func, "percentrank"}}.
{FREQUENCY} : {token, {func, "frequency"}}.
{SIGN} : {token, {func, "sign"}}.
{POWER} : {token, {func, "power"}}.
{DCOUNTA} : {token, {func, "dcounta"}}.
{HARMEAN} : {token, {func, "harmean"}}.
{PROPER} : {token, {func, "proper"}}.
{LOG} : {token, {func, "log"}}.
{FISHERINV} : {token, {func, "fisherinv"}}.
{STDEVA} : {token, {func, "stdeva"}}.
{MAX} : {token, {func, "max"}}.
{LARGE} : {token, {func, "large"}}.
{DSTDEVP} : {token, {func, "dstdevp"}}.
{INDIRECT} : {token, {func, "indirect"}}.
{MDETERM} : {token, {func, "mdeterm"}}.
{PPMT} : {token, {func, "ppmt"}}.
{TIME} : {token, {func, "time"}}.
{NORMINV} : {token, {func, "norminv"}}.
{RSQ} : {token, {func, "rsq"}}.
{DPRODUCT} : {token, {func, "dproduct"}}.
{ISNUMBER} : {token, {func, "isnumber"}}.
{TODAY} : {token, {func, "today"}}.
{DAYS360} : {token, {func, "days360"}}.
{CONCATENATE} : {token, {func, "concatenate"}}.
{NPER} : {token, {func, "nper"}}.
{LINEST} : {token, {func, "linest"}}.
{CRITBINOM} : {token, {func, "critbinom"}}.
{FDIST} : {token, {func, "fdist"}}.
{FLOOR} : {token, {func, "floor"}}.
{DB} : {token, {func, "db"}}.
{COUNTBLANK} : {token, {func, "countblank"}}.
{DSUM} : {token, {func, "dsum"}}.
{ASINH} : {token, {func, "asinh"}}.
{CHAR} : {token, {func, "char"}}.
{KURT} : {token, {func, "kurt"}}.
{STDEV} : {token, {func, "stdev"}}.
{ROWS} : {token, {func, "rows"}}.
{SUMPRODUCT} : {token, {func, "sumproduct"}}.
{VAR} : {token, {func, "var"}}.
{DATEVALUE} : {token, {func, "datevalue"}}.
{IRR} : {token, {func, "irr"}}.
{CHOOSE} : {token, {func, "choose"}}.
{TIMEVALUE} : {token, {func, "timevalue"}}.
{PERMUT} : {token, {func, "permut"}}.
{DEGREES} : {token, {func, "degrees"}}.
{COUNT} : {token, {func, "count"}}.
{MINVERSE} : {token, {func, "minverse"}}.
{MID} : {token, {func, "mid"}}.
{ISTEXT} : {token, {func, "istext"}}.
{VARP} : {token, {func, "varp"}}.
{STANDARDIZE} : {token, {func, "standardize"}}.
{LEFT} : {token, {func, "left"}}.
{ROUNDDOWN} : {token, {func, "rounddown"}}.
{COUNTA} : {token, {func, "counta"}}.
{AVERAGE} : {token, {func, "average"}}.
{STDEVP} : {token, {func, "stdevp"}}.
{COLUMN} : {token, {func, "column"}}.
{SUMIF} : {token, {func, "sumif"}}.
{STEYX} : {token, {func, "steyx"}}.
{LEN} : {token, {func, "len"}}.
{GAMMALN} : {token, {func, "gammaln"}}.
{SUMX2MY2} : {token, {func, "sumx2my2"}}.
{PMT} : {token, {func, "pmt"}}.
{FALSE} : {token, {func, "false"}}.
{INTERSECT} : {token, {func, "intersect"}}.
{GAMMADIST} : {token, {func, "gammadist"}}.
{SUMSQ} : {token, {func, "sumsq"}}.
{EVEN} : {token, {func, "even"}}.
{ATAN2} : {token, {func, "atan2"}}.
{EXPONDIST} : {token, {func, "expondist"}}.
{TRANSPOSE} : {token, {func, "transpose"}}.
{VARPA} : {token, {func, "varpa"}}.
{ABS} : {token, {func, "abs"}}.
{AND} : {token, {func, "and"}}.
{ISBLANK} : {token, {func, "isblank"}}.
{MOD} : {token, {func, "mod"}}.
{SUBSTITUTE} : {token, {func, "substitute"}}.
{SYD} : {token, {func, "syd"}}.
{ACOS} : {token, {func, "acos"}}.
{NORMSINV} : {token, {func, "normsinv"}}.
{SUMX2PY2} : {token, {func, "sumx2py2"}}.
{SUBTOTAL} : {token, {func, "subtotal"}}.
{NORMDIST} : {token, {func, "normdist"}}.
{MIN} : {token, {func, "min"}}.
{DAVERAGE} : {token, {func, "daverage"}}.
{TEXT} : {token, {func, "text"}}.
{TAN} : {token, {func, "tan"}}.
{ROW} : {token, {func, "row"}}.
{MAXA} : {token, {func, "maxa"}}.
{MINA} : {token, {func, "mina"}}.
{DOLLAR} : {token, {func, "dollar"}}.
{MIRR} : {token, {func, "mirr"}}.
{TRUNC} : {token, {func, "trunc"}}.
{DMAX} : {token, {func, "dmax"}}.
{QUARTILE} : {token, {func, "quartile"}}.
{DEVSQ} : {token, {func, "devsq"}}.
{INT} : {token, {func, "int"}}.

\n : {end_token, {'$end'}}.
.  : {token, {stuff, YYtext}}.

