-define(FNS_EN_GB, {array, [{array, ["Database","DGET",
  "Extracts a single record from a list or database than meets the criteria."]},
 {array, ["Date and Time","WEEKDAY",
  "Returns the day of the week from a date as an integer (with Sunday=1). "]},
 {array, ["Maths And Trigonometry","SIN",
  "Returns the sine of an angle expressed as radians."]},
 {array, ["Database","DAVERAGE",
  "Averages the values in a field (column) of records in a list or database that match conditions you specify."]},
 {array, ["Date and Time","SECOND","Returns the seconds value from a time value."]},
 {array, ["Information","ISERROR",
  "Checks whether a cell value is an error and returns TRUE or FALSE"]},
 {array, ["Maths And Trigonometry","POWER",
  "Returns the result of a number raised by a specified power."]},
 {array, ["Financial","SYD",
  "Returns the sum-of-years' digits depreciation of an asset for a specified period."]},
 {array, ["Maths And Trigonometry","MOD",
  "Returns the remainder of a number divided by another number."]},
 {array, ["Statistical","MIN","Returns the smallest value in a range of values."]},
 {array, ["Financial","PV","Returns the present value of an investment."]},
 {array, ["Logical","NOT","Changes logical value e.g. From FALSE to TRUE"]},
 {array, ["Statistical","COUNTBLANK","Counts the number of empty cells."]},
 {array, ["Logical","AND",
  "Returns true if all the logic arguments supplied evaluate to TRUE. "]},
 {array, ["Statistical","AVERAGE","Returns the average of a range of numbers"]},
 {array, ["Text","PROPER","Capitalises the first letter in a text string."]},
 {array, ["Truncation","INT","Rounds a number down to the nearest integer value."]},
 {array, ["Information","ISTEXT",
  "Checks whether a cell value is text and returns TRUE or FALSE"]},
 {array, ["Maths And Trigonometry","ACOS",
  "Returns the arccosine of a number between -1 and 1. The arccosine is the angle whose cosine is the number. The angle is given in radians from 0 to pi. "]},
 {array, ["Text","UPPER","Converts text to uppercase."]},
 {array, ["Text","LEN","Returns the length (number of characters) in a string."]},
 {array, ["Lookup and Reference","ROWS",
  "Returns the number of rows in an array/range."]},
 {array, ["Text","SUBSTITUTE","Substitutes new for old text in a text string."]},
 {array, ["Text","EXACT",
  "Compares two text strings and returns TRUE if they are an exact match or FALSE otherwise."]},
 {array, ["Date and Time","MINUTE","Returns the minute value from a time value."]},
 {array, ["Lookup and Reference","HLOOKUP",
  "Searches for a value in the top row of an array and returns the value in the row specified to get the value from."]},
 {array, ["Hypernumbers","TEXTAREA","Create a textarea"]},
 {array, ["Date and Time","DATE",
  "Returns the internal software serial number of a date.&nbsp;"]},
 {array, ["Financial","RATE","Caculates the interest rate per period for an annuity."]},
 {array, ["Logical","true","Returns the logical value of TRUE."]},
 {array, ["Logical","OR",
  "Returns TRUE if any of the logic arguments supplied evaluate to TRUE. Otherwise FALSE."]},
 {array, ["Maths And Trigonometry","LN",
  "Returns the natural (base e) logarithm of a number."]},
 {array, ["Statistical","COUNTIF",
  "Counts the number of cells in a range that meet a given condition."]},
 {array, ["Hypernumbers","INCLUDE","Includes the range as rendered html"]},
 {array, ["Database","DSUM","Calculates the sum of values for a field in a database."]},
 {array, ["Financial","NPER",
  "Returns the number of periods for an investment based on periodic constant payments and interest rate."]},
 {array, ["Logical","false","Retuns a logical value of FALSE."]},
 {array, ["Maths And Trigonometry","DEGREES","Converts radians to degrees."]},
 {array, ["Statistical","COUNT","Counts the number of cells with numbers."]},
 {array, ["Text","REPLACE",
  "Replaces part of a text string with the specified characters."]},
 {array, ["Truncation","TRUNC",
  "Truncates a number to a specified number of decimal places."]},
 {array, ["Truncation","ROUND","Rounds a number to the specified round-off unit."]},
 {array, ["Database","DMIN",
  "Returns the minimum value in a field (column) of records in a list or database that match conditions you specify."]},
 {array, ["Financial","DDB","Returns the depreceiation of an asset."]},
 {array, ["Information","N","Converts non-number values to numbers"]},
 {array, ["Maths And Trigonometry","SUM",
  "calculates the sum of all the numbers specified."]},
 {array, ["Maths And Trigonometry","ATAN",
  "Returns the arctangent of a number. The arctangent is the angle whose tangent is the number. The angle is given in radians from -pi/2 to pi/2. "]},
 {array, ["Text","VALUE",
  "Converts a text string that represents a number to a number."]},
 {array, ["Text","LOWER","Converts all characters in a string to lower case."]},
 {array, ["Database","DCOUNTA",
  "Counts the number of non-blank records in a list or database that match conditions you specify."]},
 {array, ["Date and Time","TODAY","Todays date."]},
 {array, ["Information","ISNONTEXT",
  "Checks whether a value is not text and returns TRUE or FALSE"]},
 {array, ["Information","ISNA",
  "Checks whether a value is #N/A and returns TRUE or FALSE"]},
 {array, ["Lookup and Reference","VLOOKUP",
  "Searches for a value in the leftmost column of an array and returns the value in the column specified to get the value from."]},
 {array, ["Maths And Trigonometry","RADIANS","Converts degrees to radians."]},
 {array, ["Text","T","Returns the value of the referenced cell."]},
 {array, ["Text","FIND","Returns the position of a character in a string."]},
 {array, ["category","function","help"]},
 {array, ["Date and Time","MONTH","Returns the month value from a date value."]},
 {array, ["Information","ISERR",
  "Checks whether a cell value is an error and returns TRUE or FALSE"]},
 {array, ["Lookup and Reference","INDEX",
  "Returns a value from within an array at the position specified by a row and column number."]},
 {array, ["Maths And Trigonometry","PI","Returns the constant PI."]},
 {array, ["Statistical","VAR",
  "Calculates the variance of a sample of numbers around the mean. Uses n-1 as the divisor."]},
 {array, ["Statistical","STDEVP",
  "Calculates the standard deviation or dispersion measure of a set of values around the mean. Uses n as the divisor."]},
 {array, ["Text","REPT","Repeat text a specified number of times."]},
 {array, ["Hypernumbers","SELECT","Create a drop down select box"]},
 {array, ["Date and Time","DAY","Returns the day of the month from a date."]},
 {array, ["Financial","SLN",
  "Returns the straight-line depreciation of an asset for one period."]},
 {array, ["Lookup and Reference","CHOOSE",
  "Uses an index number to select from a list of values."]},
 {array, ["Maths And Trigonometry","LOG",
  "Returns the logarithm of a number for any specified base."]},
 {array, ["Statistical","MAX","Returns the largest value in a range of values."]},
 {array, ["Hypernumbers","INPUT","Create a single line text input"]},
 {array, ["Database","DVAR",
  "Estimates the variance for a field in a sample from a database."]},
 {array, ["Financial","PMT",
  "Calculates the payment amount for a loan over a number of periods at a fixed interest rate."]},
 {array, ["Financial","NPV",
  "Calculates the net present value of an investment by using a discount rate and a series of future payments (negative values) and income (positive values)."]},
 {array, ["Logical","IF","Use conditional logic in calculations."]},
 {array, ["Maths And Trigonometry","EXP",
  "Exponetial of a number is e (=2.71828182845905) raised to the power of the input number. "]},
 {array, ["Statistical","COUNTA","Counts the number of cells that are not empty."]},
 {array, ["Hypernumbers","TWITTER.BUTTON",
  "Embed a twitter \"follow me\" button onto your page, name is your username, x is optional and a number from 0-5 which changes the style of the button"]},
 {array, ["Database","DPRODUCT",
  "Multiplies the values in a field that meets certain criteria."]},
 {array, ["Financial","FV","Returns the future value of an investment."]},
 {array, ["Information","NA","Returns (value not available) #N/A"]},
 {array, ["Maths And Trigonometry","TAN",
  "Returns the tangent of an angle - entered as radians."]},
 {array, ["Maths And Trigonometry","SUMIF",
  "Returns the sum of numbers in a range of cells that satisfy a specified criteria. For example =SUMIF(a1:a4, \">2\") will sum up the values in a1:a4 only where the cell is >2. The cells to be summed can be from a different range."]},
 {array, ["Maths And Trigonometry","ATAN2",
  "Returns the arctangent or angle between the x-axis and a line extending from the origin to some (x,y) coordinates. The angle is given in radians from -pi to pi. "]},
 {array, ["Text","MID","Extracts a substring from a larger string."]},
 {array, ["Truncation","EVEN","Returns number up to the nearest even integer. "]},
 {array, ["Information","ISNUMBER",
  "Checks whether a cell value is a number and returns TRUE or FALSE"]},
 {array, ["Maths And Trigonometry","ABS","Returns the absolute value of a number."]},
 {array, ["Text","TRIM",
  "Removes spaces from text except for single spacing between words."]},
 {array, ["Text","LEFT",
  "Extracts the left most characters in a string specified by num_chars. The default is the leftmost character if num_chars is omitted."]},
 {array, ["Date and Time","NOW",{array, []}]},
 {array, ["Lookup and Reference",{array, []},
  "Returns the relative position of a value in a range of values."]},
 {array, ["Statistical","VARP",
  "Calculates the variance of a sample of numbers around the mean. Uses n as the divisor."]},
 {array, ["Text","RIGHT",
  "Returns the rightmost non-missing characters from a text string given the number of characters required."]},
 {array, ["Hypernumbers","RADIO","Create a set of radio buttons"]},
 {array, ["Date and Time","HOUR","Returns the hour of a time value."]},
 {array, ["Lookup and Reference","COLUMNS",
  "Ruturns the number of columns in an array/range."]},
 {array, ["Maths And Trigonometry","LOG10",
  "Returns the logarithm to base 10 of a number."]},
 {array, ["Hypernumbers","BUTTON","Create a button with its value set to text"]},
 {array, ["Database","DVARP","Estimates the variance for a field in a database."]},
 {array, ["Maths And Trigonometry","FACT",
  "Returns factorial of a number. E.g. Fact(4)=4*3*2*1=24."]},
 {array, ["Hypernumbers","GOOGLE.MAP",
  "Embed a google map that centers at Latitude, Longitude, the zoom level is a number between 1 and 20. (the map will preview as an image inside the spreadsheet)"]},
 {array, ["Database","DSTDEVP",
  "Calculates the standard deviation for a field in a sample from a database."]},
 {array, ["Database","DSTDEV",
  "Calculates the standard deviation for a field in a database."]},
 {array, ["Financial","IRR",
  "returns tyhe internal rate of return for a series of cash flows."]},
 {array, ["Maths And Trigonometry","COS",
  "Returns the cosine of an angle - supplied as radians."]},
 {array, ["Database","DMAX",
  "Returns the maximum value in a field (column) of records in a list or database that match conditions you specify."]},
 {array, ["Date and Time","YEAR","Returns the year value for a given date."]},
 {array, ["Maths And Trigonometry","SQRT",
  "Returns the square root of a number. For info =SQRT(4) is equivalent to using =4^0.5 or power(4,0.5)."]},
 {array, ["Maths And Trigonometry","ASIN",
  "Returns the arcsine of a number between -1 and 1. The arcsine is the angle whose sine is the number. The angle is given in radians from -pi/2 to pi/2. "]},
 {array, ["Database","DCOUNT",
  "Counts the number of values in a list or database that match conditions you specify."]},
 {array, ["Date and Time","TIME",
  "Returns the decimal fraction of days time in terms of 24 hours."]},
 {array, ["Information","ISLOGICAL",
  "Checks whether a cell has a logical value of (TRUE or FALSE) and returns TRUE or FALSE"]},
 {array, ["Maths And Trigonometry","PRODUCT",
  "Returns the product of multiplying numbers e.g. =PRODUCT(1, 2, 3) is the same as =1x2x3."]},
 {array, ["Information","ISBLANK",
  "Checks whether a cell is empty and returns TRUE or FALSE"]},
 {array, ["Maths And Trigonometry","ODD",
  "Returns a number rounded up to the nearest odd integer."]},
 {array, ["Statistical","STDEV",
  "Calculates the standard deviation or dispersion measure of a set of values around the mean. Uses n-1 as the divisor."]}]}).
