-define(RG_cell,"^[a-zA-Z]+[0-9]+$").                 % ". syntax highlighting
-define(RG_range,"^[a-zA-Z]+[0-9]+:[a-zA-Z]+[0-9]+$").% ". syntax highlighting
-define(RG_col_range,"^[a-zA-Z]+:[a-zA-Z]+$").        % ". syntax highlighting
-define(RG_row_range,"^[0-9]+:[0-9]+$").              % ". syntax highlighting
-define(RG_num,"(^-?[0-9]+\\.[0-9]*$)|(^[0-9]*$)").   % ". syntax highlighting
