%%-*-erlang-*-
%% this is a permissions script for creating a new site
%%

{add_view, 
 [{path, []},
  {perms, [{group, "admin"}]},
  {view, "_g/tiny/tiny"}
 ]}.
{add_view, 
 [{path, []},
  {perms, [{group, "admin"}]},
  {view, "_g/core/spreadsheet"}
 ]}.
{champion,
 [{path, []},
  {view, "_g/tiny/tiny"}
 ]}.

{add_view, 
 [{path, ["_user", "login"]},
  {perms, [everyone]},
  {view, "_g/core/login"}
 ]}.
{champion,
 [{path, ["public"]},
  {view, "_g/core/login"}
 ]}.
