#!/bin/bash Batch file to generate test files
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\simple.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\just_numbers.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\quadratic_equations.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\arithmetic_and_precedence.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\booleans_and_errors.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\simple_arrays_and_ranges.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\sum_with_one_arg.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\block_of_numbers.xls"
readexcel_win_z "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\z_basic_functions_tests_a_e.xls"
readexcel_win_z "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\z_basic_functions_tests_f_k.xls"
readexcel_win_z "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\z_basic_functions_tests_l_t.xls"
readexcel_win_z "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\z_basic_functions_tests_u_z.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\nested_functions_spaces_crs.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\array_formulae.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\three_dee_ref.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\basic_unicode_strings.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\made_up_fn_names.xls"

readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_address.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_date_and_time.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_db.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_engineering.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_financial.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_information.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_logical.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_lookup.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_maths.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_operators.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_stats.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_text.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_bitwise.xls"
readexcel_win "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\files\Win Excel 2007 (as 97)\gnumeric_trig.xls"

generatetest "simple.xls.yaml"
generatetest "just_numbers.xls.yaml"
generatetest "quadratic_equations.xls.yaml"
generatetest "arithmetic_and_precedence.xls.yaml"
generatetest "booleans_and_errors.xls.yaml"
generatetest "simple_arrays_and_ranges.xls.yaml"
generatetest "sum_with_one_arg.xls.yaml"
generatetest "block_of_numbers.xls.yaml"
generatetest "z_basic_functions_tests_a_e.xls.yaml"
generatetest "z_basic_functions_tests_f_k.xls.yaml"
generatetest "z_basic_functions_tests_l_t.xls.yaml"
generatetest "z_basic_functions_tests_u_z.xls.yaml"
generatetest "nested_functions_spaces_crs.xls.yaml"
generatetest "array_formulae.xls.yaml"
generatetest "three_dee_ref.xls.yaml"
generatetest "basic_unicode_strings.xls.yaml"
generatetest "made_up_fn_names.xls.yaml"

generatetest "gnumeric_address.xls.yaml"
generatetest "gnumeric_date_and_time.xls.yaml"
generatetest "gnumeric_db.xls.yaml"
generatetest "gnumeric_engineering.xls.yaml"
generatetest "gnumeric_financial.xls.yaml"
generatetest "gnumeric_information.xls.yaml"
generatetest "gnumeric_logical.xls.yaml"
generatetest "gnumeric_lookup.xls.yaml"
generatetest "gnumeric_maths.xls.yaml"
generatetest "gnumeric_operators.xls.yaml"
generatetest "gnumeric_stats.xls.yaml"
generatetest "gnumeric_text.xls.yaml"
generatetest "gnumeric_bitwise.xls.yaml"
generatetest "gnumeric_trig.xls.yaml"

move "simple_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "just_numbers_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "quadratic_equations_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "arithmetic_and_precedence_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "booleans_and_errors_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "simple_arrays_and_ranges_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "sum_with_one_arg_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "block_of_numbers_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "z_basic_functions_tests_a_e_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "z_basic_functions_tests_f_k_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "z_basic_functions_tests_l_t_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "z_basic_functions_tests_u_z_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "nested_functions_spaces_crs_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "array_formulae_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "three_dee_ref_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "basic_unicode_strings_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "made_up_fn_names_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"

move "gnumeric_address_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move gnumeric_date_and_time_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "gnumeric_db_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "gnumeric_engineering_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "gnumeric_financial_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "gnumeric_information_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "gnumeric_logical_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "gnumeric_lookup_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "gnumeric_maths_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "gnumeric_operators_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "gnumeric_stats_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "gnumeric_text_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "gnumeric_bitwise_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
move "gnumeric_trig_SUITE.erl" "c:\Users\Gordon Guthrie\Documents\SVN\code\trunk\testroot\excel_import_test\"
