var OA_output = new Array(); 
OA_output['Sidebar 1'] = '';
OA_output['Sidebar 1'] += "<"+"!--<"+"span class=\"declare\">Advertisement<"+"/span>-->\n";
OA_output['Sidebar 1'] += "<"+"div style=\"height:20px;\"><"+"/div><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5802__zoneid=40__OXLCA=1__cb=71def4b5f7__oadest=http%3A%2F%2Fwww.lightcms.com%2Ffor-designers%3Futm_source%3DSmashing%252B%28Sidebar%29%26utm_medium%3Dbanner%26utm_content%3DHTML-Green%26utm_campaign%3DSmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=html-green-190x400_4.png&contenttype=png\' width=\'190\' height=\'400\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_71def4b5f7\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5802&amp;campaignid=2067&amp;zoneid=40&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=71def4b5f7\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sidebar 3'] = '';

OA_output['Medium Rectangle'] = '';
OA_output['Medium Rectangle'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5824__zoneid=22__OXLCA=1__cb=a1ed2bbc6a__oadest=http%3A%2F%2Fwww.LogoDesignTeam.com\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ldt-300x250-01_2.gif&contenttype=gif\' width=\'300\' height=\'250\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_a1ed2bbc6a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5824&amp;campaignid=2078&amp;zoneid=22&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=a1ed2bbc6a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Comment spnsr'] = '';
OA_output['Comment spnsr'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5791__zoneid=26__OXLCA=1__cb=50c129ff60__oadest=http%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Comment%29%26utm_medium%3Dbanner%26utm_content%3DSwitcher%252B%28Title%252BOnly%29%26utm_campaign%3DSmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=switcher_title_468_10.png&contenttype=png\' width=\'468\' height=\'90\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_50c129ff60\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5791&amp;campaignid=2064&amp;zoneid=26&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=50c129ff60\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Logo'] = '';

OA_output['Textad'] = '';
OA_output['Textad'] += "<"+"div id=\"textad\"><"+"div style=\"padding: 1em !important; margin-top: 0.75em; background-color: rgba(0,0,0,0.05); border-radius: 8px;\">\n";
OA_output['Textad'] += "<"+"div id=\"mc_embed_signup\" class=\"sm-search\">\n";
OA_output['Textad'] += "<"+"p>Every other Tuesday we send out our lovely <"+"strong style=\"font-family: \'Proxima Nova Bold\', Arial, Verdana, sans-serif;\">email newsletter<"+"/strong> with useful tips and techniques, recent articles and upcoming events. 145,000 readers have signed up already. Why don\'t you sign up, too?<"+"/p>\n";
OA_output['Textad'] += "<"+"form  action=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php\' method=\'GET\' id=\"mc-embedded-subscribe-form\" name=\"mc-embedded-subscribe-form\" class=\"validate\" target=\'_self\'>\n";
OA_output['Textad'] += "<"+"input name=\"EMAIL\" style=\"width: 45%;\" type=\"text\" placeholder=\"Your email\">\n";
OA_output['Textad'] += "<"+"button class=\"search_submit\" type=\"submit\"><"+"span class=\"first-type\">Sign up!<"+"/span><"+"/button>\n";
OA_output['Textad'] += "<"+"input type=\'hidden\' name=\'oaparams\' value=\'2__bannerid=3452__zoneid=68__OXLCA=1__cb=969d930a1b__oadest=http://smashingmagazine.us1.list-manage1.com/subscribe/post?u=16b832d9ad4b28edf261f34df&amp;id=a1666656e0\'><"+"/form>\n";
OA_output['Textad'] += "<"+"/div>\n";
OA_output['Textad'] += "<"+"/div><"+"div id=\'beacon_969d930a1b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=3452&amp;campaignid=1018&amp;zoneid=68&amp;loc=1&amp;referer=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=969d930a1b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['Sidebar Special'] = '';
OA_output['Sidebar Special'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5804__zoneid=72__OXLCA=1__cb=79f0134443__oadest=http%3A%2F%2Fwww.lightcms.com%2Ffor-designers%3Futm_source%3DSmashing%252B%28420x200%29%26utm_medium%3Dbanner%26utm_content%3DLovedByDesigners%26utm_campaign%3DSmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=loved-420x200_8.png&contenttype=png\' width=\'420\' height=\'200\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_79f0134443\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5804&amp;campaignid=2068&amp;zoneid=72&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=79f0134443\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['VIS 1'] = '';
OA_output['VIS 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4360__zoneid=70__OXLCA=1__cb=279653a2b1__oadest=http%3A%2F%2Fw3-markup.com\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=banner_w3m_200x125.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'PSD to HTML\' title=\'PSD to HTML\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4360__zoneid=70__OXLCA=1__cb=279653a2b1__oadest=http%3A%2F%2Fw3-markup.com\' target=\'_blank\'>PSD to HTML<"+"/a><"+"div id=\'beacon_279653a2b1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4360&amp;campaignid=135&amp;zoneid=70&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=279653a2b1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['VIS 2'] = '';

OA_output['VIS 3'] = '';

OA_output['VIS 4'] = '';

OA_output['VIS 5'] = '';

OA_output['VIS 6'] = '';

OA_output['VIS 7'] = '';

OA_output['VIS 8'] = '';

OA_output['VIS 9'] = '';

OA_output['VIS 10'] = '';

OA_output['spnsr ROS 1'] = '';
OA_output['spnsr ROS 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5617__zoneid=24__OXLCA=1__cb=814a1e066d__oadest=http%3A%2F%2Fwww.stickermule.com%3Futm_campaign%3DSmashing_Branded%26utm_medium%3DBanner%26utm_source%3DSmashing_Mag\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=image_6.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Custom Stickers\' title=\'Custom Stickers\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5617__zoneid=24__OXLCA=1__cb=814a1e066d__oadest=http%3A%2F%2Fwww.stickermule.com%3Futm_campaign%3DSmashing_Branded%26utm_medium%3DBanner%26utm_source%3DSmashing_Mag\' target=\'_blank\'>Custom Stickers<"+"/a><"+"div id=\'beacon_814a1e066d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5617&amp;campaignid=1996&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=814a1e066d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 2'] = '';
OA_output['spnsr ROS 2'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5736__zoneid=24__OXLCA=1__cb=91355145e0__oadest=http%3A%2F%2Fwww.sitefinity.com%2Fcampaigns%2Fwhitepapers%2Fthree-steps-to-a-better-mobile-strategy%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_campaign%3Dsmmag_mobilewhitepaper\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=sitefinity_banner_5.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Web Content Management.\' title=\'Web Content Management.\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5736__zoneid=24__OXLCA=1__cb=91355145e0__oadest=http%3A%2F%2Fwww.sitefinity.com%2Fcampaigns%2Fwhitepapers%2Fthree-steps-to-a-better-mobile-strategy%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_campaign%3Dsmmag_mobilewhitepaper\' target=\'_blank\'>Web Content Management.<"+"/a><"+"div id=\'beacon_91355145e0\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5736&amp;campaignid=2047&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=91355145e0\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 3'] = '';
OA_output['spnsr ROS 3'] += "<"+"script src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=rsb&c=28&pli=6080755&PluID=0&w=200&h=125&9e37204e48&ncu=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5223__zoneid=24__OXLCA=1__cb=9e37204e48__oadest=&ucm=true\"><"+"/script>\n";
OA_output['spnsr ROS 3'] += "<"+"noscript>\n";
OA_output['spnsr ROS 3'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5223__zoneid=24__OXLCA=1__cb=9e37204e48__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080755%26Page%3D%26PluID%3D0%26Pos%3D777\" target=\"_blank\"><"+"img src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=bsr&FlightID=6080755&Page=&PluID=0&Pos=777\" border=0 width=200 height=125><"+"/a>\n";
OA_output['spnsr ROS 3'] += "<"+"/noscript>\n";
OA_output['spnsr ROS 3'] += "<"+"br>\n";
OA_output['spnsr ROS 3'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5223__zoneid=24__OXLCA=1__cb=9e37204e48__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080755%26Page%3D%26PluID%3D0%26Pos%3D777\" target=\"_blank\">Create free stunning sites!<"+"/a><"+"div id=\'beacon_9e37204e48\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5223&amp;campaignid=130&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=9e37204e48\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 4'] = '';
OA_output['spnsr ROS 4'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5809__zoneid=24__OXLCA=1__cb=95cf5eca5a__oadest=http%3A%2F%2Fwww.lightcms.com%2Ffor-designers%3Futm_source%3DSmashing%252B%28Sponsor%29%26utm_medium%3Dbanner%26utm_content%3DHTML-Green%26utm_campaign%3DSmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=html-green-200x125_8.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Sign Up for Free!\' title=\'Sign Up for Free!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5809__zoneid=24__OXLCA=1__cb=95cf5eca5a__oadest=http%3A%2F%2Fwww.lightcms.com%2Ffor-designers%3Futm_source%3DSmashing%252B%28Sponsor%29%26utm_medium%3Dbanner%26utm_content%3DHTML-Green%26utm_campaign%3DSmashing\' target=\'_blank\'>Sign Up for Free!<"+"/a><"+"div id=\'beacon_95cf5eca5a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5809&amp;campaignid=2069&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=95cf5eca5a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 5'] = '';
OA_output['spnsr ROS 5'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5753__zoneid=24__OXLCA=1__cb=cdb047afcb__oadest=http%3A%2F%2Fpsd2html.com%2F%3Futm_source%3Dsmashingmagazine.com%26utm_medium%3Dbanner%26utm_campaign%3Dnew-p2h\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_blue_7.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'PSD2HTML.com\' title=\'PSD2HTML.com\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5753__zoneid=24__OXLCA=1__cb=cdb047afcb__oadest=http%3A%2F%2Fpsd2html.com%2F%3Futm_source%3Dsmashingmagazine.com%26utm_medium%3Dbanner%26utm_campaign%3Dnew-p2h\' target=\'_blank\'>PSD2HTML.com<"+"/a><"+"div id=\'beacon_cdb047afcb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5753&amp;campaignid=1626&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=cdb047afcb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 6'] = '';
OA_output['spnsr ROS 6'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=2877__zoneid=24__OXLCA=1__cb=b019940bbc__oadest=http%3A%2F%2Fwww.dreamtemplate.com%2F%3Fref%3Dsm\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125-dt-2.gif&contenttype=gif\' width=\'200\' height=\'125\' alt=\'Premium Web Templates\' title=\'Premium Web Templates\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=2877__zoneid=24__OXLCA=1__cb=b019940bbc__oadest=http%3A%2F%2Fwww.dreamtemplate.com%2F%3Fref%3Dsm\' target=\'_blank\'>Premium Web Templates<"+"/a><"+"div id=\'beacon_b019940bbc\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=2877&amp;campaignid=1026&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=b019940bbc\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 7'] = '';
OA_output['spnsr ROS 7'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5609__zoneid=24__OXLCA=1__cb=b8660a4e86__oadest=http%3A%2F%2Fwww.zoho.com%2Fprojects%2Flp%2Fproject-management-and-collaboration.html\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125-projects-122712_8.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Online Project Management\' title=\'Online Project Management\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5609__zoneid=24__OXLCA=1__cb=b8660a4e86__oadest=http%3A%2F%2Fwww.zoho.com%2Fprojects%2Flp%2Fproject-management-and-collaboration.html\' target=\'_blank\'>Online Project Management<"+"/a><"+"div id=\'beacon_b8660a4e86\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5609&amp;campaignid=1990&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=b8660a4e86\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 8'] = '';
OA_output['spnsr ROS 8'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4588__zoneid=24__OXLCA=1__cb=5be5e96ec2__oadest=http%3A%2F%2Fmarkup-service.com%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=banner_ms_smashing.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4588__zoneid=24__OXLCA=1__cb=5be5e96ec2__oadest=http%3A%2F%2Fmarkup-service.com%2F\' target=\'_blank\'>PSD to HTML5/CSS3<"+"/a><"+"div id=\'beacon_5be5e96ec2\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4588&amp;campaignid=1625&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=5be5e96ec2\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 9'] = '';
OA_output['spnsr ROS 9'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5891__zoneid=24__OXLCA=1__cb=742b504aa5__oadest=http%3A%2F%2Fwww.zoomyimages.com\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=smag_sponsad_1.4.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Quality Stock Images &amp; Music\' title=\'Quality Stock Images &amp; Music\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5891__zoneid=24__OXLCA=1__cb=742b504aa5__oadest=http%3A%2F%2Fwww.zoomyimages.com\' target=\'_blank\'>Quality Stock Images &amp; Music<"+"/a><"+"div id=\'beacon_742b504aa5\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5891&amp;campaignid=2104&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=742b504aa5\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 10'] = '';
OA_output['spnsr ROS 10'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5611__zoneid=24__OXLCA=1__cb=d73352c165__oadest=http%3A%2F%2Fwww.philau.edu%2Fmsintdesign%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=msidm-32513.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Get your Master&#039;s degree!\' title=\'Get your Master&#039;s degree!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5611__zoneid=24__OXLCA=1__cb=d73352c165__oadest=http%3A%2F%2Fwww.philau.edu%2Fmsintdesign%2F\' target=\'_blank\'>Get your Master&#039;s degree!<"+"/a><"+"div id=\'beacon_d73352c165\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5611&amp;campaignid=1991&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=d73352c165\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 11'] = '';
OA_output['spnsr ROS 11'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5768__zoneid=24__OXLCA=1__cb=0b0178f7aa__oadest=http%3A%2F%2Fdashboard.webydo.com%2Flandingpages%2Fstarta.aspx%3Fcampaign%3DSM\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200_125_a_7.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Freedom of Website Design\' title=\'Freedom of Website Design\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5768__zoneid=24__OXLCA=1__cb=0b0178f7aa__oadest=http%3A%2F%2Fdashboard.webydo.com%2Flandingpages%2Fstarta.aspx%3Fcampaign%3DSM\' target=\'_blank\'>Freedom of Website Design<"+"/a><"+"div id=\'beacon_0b0178f7aa\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5768&amp;campaignid=2057&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=0b0178f7aa\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 12'] = '';
OA_output['spnsr ROS 12'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5822__zoneid=24__OXLCA=1__cb=8a7df0e2fc__oadest=http%3A%2F%2Fwww.instiller.co.uk\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=instiller_ad.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Email marketing for agencies\' title=\'Email marketing for agencies\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5822__zoneid=24__OXLCA=1__cb=8a7df0e2fc__oadest=http%3A%2F%2Fwww.instiller.co.uk\' target=\'_blank\'>Email marketing for agencies<"+"/a><"+"div id=\'beacon_8a7df0e2fc\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5822&amp;campaignid=2076&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=8a7df0e2fc\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 13'] = '';
OA_output['spnsr ROS 13'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5847__zoneid=24__OXLCA=1__cb=94214d8f1f__oadest=http%3A%2F%2Fwww.icenium.com%2F%3Futm_source%3Dsmashingmag%26utm_medium%3Dbanner%26utm_campaign%3Dhp1\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_icenium_smashing_2.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Cross-platform mobile development\' title=\'Cross-platform mobile development\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5847__zoneid=24__OXLCA=1__cb=94214d8f1f__oadest=http%3A%2F%2Fwww.icenium.com%2F%3Futm_source%3Dsmashingmag%26utm_medium%3Dbanner%26utm_campaign%3Dhp1\' target=\'_blank\'>Cross-platform mobile development<"+"/a><"+"div id=\'beacon_94214d8f1f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5847&amp;campaignid=2091&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=94214d8f1f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 14'] = '';
OA_output['spnsr ROS 14'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5182__zoneid=24__OXLCA=1__cb=201faaac40__oadest=http%3A%2F%2Fwww.typekit.com%2F%3Futm_source%3Dsmashingmagazine%26utm_medium%3DDisplay%26utm_content%3Dshwf120515%26utm_campaign%3DGeneral\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=typekit-ad-200x125-1_18.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Web fonts with Typekit\' title=\'Web fonts with Typekit\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5182__zoneid=24__OXLCA=1__cb=201faaac40__oadest=http%3A%2F%2Fwww.typekit.com%2F%3Futm_source%3Dsmashingmagazine%26utm_medium%3DDisplay%26utm_content%3Dshwf120515%26utm_campaign%3DGeneral\' target=\'_blank\'>Web fonts with Typekit<"+"/a><"+"div id=\'beacon_201faaac40\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5182&amp;campaignid=1850&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=201faaac40\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 15'] = '';
OA_output['spnsr ROS 15'] += "<"+"script src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=rsb&c=28&pli=6080749&PluID=0&w=200&h=125&4cddcd4f5a&ncu=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5222__zoneid=24__OXLCA=1__cb=4cddcd4f5a__oadest=&ucm=true\"><"+"/script>\n";
OA_output['spnsr ROS 15'] += "<"+"noscript>\n";
OA_output['spnsr ROS 15'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5222__zoneid=24__OXLCA=1__cb=4cddcd4f5a__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080749%26Page%3D%26PluID%3D0%26Pos%3D6429\" target=\"_blank\"><"+"img src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=bsr&FlightID=6080749&Page=&PluID=0&Pos=6429\" border=0 width=200 height=125><"+"/a>\n";
OA_output['spnsr ROS 15'] += "<"+"/noscript>\n";
OA_output['spnsr ROS 15'] += "<"+"br><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5222__zoneid=24__OXLCA=1__cb=4cddcd4f5a__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080749%26Page%3D%26PluID%3D0%26Pos%3D6429\" target=\"_blank\">Create free stunning sites!<"+"/a><"+"div id=\'beacon_4cddcd4f5a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5222&amp;campaignid=250&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=4cddcd4f5a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 16'] = '';
OA_output['spnsr ROS 16'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5622__zoneid=24__OXLCA=1__cb=d00256ed63__oadest=http%3A%2F%2Fwww.shopify.com%2Ftour%2Ffor-designers%3Futm_source%3Dsmag%26utm_medium%3Dsmag%26utm_campaign%3Ddesigners\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=smashing-ad_2.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Shopify- ecommerce done right\' title=\'Shopify- ecommerce done right\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5622__zoneid=24__OXLCA=1__cb=d00256ed63__oadest=http%3A%2F%2Fwww.shopify.com%2Ftour%2Ffor-designers%3Futm_source%3Dsmag%26utm_medium%3Dsmag%26utm_campaign%3Ddesigners\' target=\'_blank\'>Shopify- ecommerce done right<"+"/a><"+"div id=\'beacon_d00256ed63\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5622&amp;campaignid=2000&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=d00256ed63\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 1'] = '';
OA_output['Sponsor XXL 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5045__zoneid=77__OXLCA=1__cb=27ad7cc0a8__oadest=http%3A%2F%2Fad.au.doubleclick.net%2Fclk%3B268093556%3B92859839%3Bk\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=410x125-4_2.jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_27ad7cc0a8\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5045&amp;campaignid=1794&amp;zoneid=77&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2013%2F03%2F12%2Fcustomizing-bootstrap%2F&amp;cb=27ad7cc0a8\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 2'] = '';

OA_output['Sponsor XXL 3'] = '';

OA_output['Sponsor XXL 4'] = '';

OA_output['Sponsor XXL 5'] = '';

OA_output['Specials'] = '';

