{application, read_excel,
	[{description,  "The read_excel application"},
	 {vsn,          "1.0"},
	 {modules,      [read_excel,
			 read_excel_sup,
			 read_file_srv,
			 filefilters,
			 build_sheet_srv,
			 excel,
	                 excel_util]},
	 {registered,   [ ]},
	 {included_applications, []},
	 {applications, [kernel, stdlib]},
	 {mod,		{read_excel, [ ]}}]}.
