% This module has been generated by gen_rev_comp_test.rb
% DO NOT EDIT MANUALLY.
%
% Source file: d_gnumeric_information.xls
% Generated on: Mon Feb 11 00:19:38 +0000 2008

-module(d_gnumeric_information_test_SUITE).
-compile(export_all).
-include("ct.hrl").


init_per_suite(Config) ->
    code:add_patha("../../../../../ebin"),
    production_boot:setup_paths(),
    Data = test_util:read_excel_file("/Win Excel 2007 (as 97)/d_gnumeric_information.xls"),
    %% io:format("in init_per_suite Data is ~p~n",[Data]),
    lists:merge([Config, [{d_gnumeric_information_test_SUITE, Data}]]).
  
end_per_suite(_Config) ->
    ok.
  
init_per_testcase(_TestCase, Config) -> Config.

end_per_testcase(_TestCase, _Config) -> ok.

read_from_excel_data(Config,{Sheet,Row,Col}) ->
  test_util:read_from_excel_data(Config,d_gnumeric_information_test_SUITE,{Sheet,Row,Col}).

sheet1_a16_test(doc) -> [{userdata,[{""}]}];
sheet1_a16_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,22.0},read_from_excel_data(Config,{"Sheet1",15,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",15,0}), {number,22.0}).
  
sheet1_a27_test(doc) -> [{userdata,[{""}]}];
sheet1_a27_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"COUNTBLANK"},read_from_excel_data(Config,{"Sheet1",26,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",26,0}), {string,"COUNTBLANK"}).
  
sheet1_a38_test(doc) -> [{userdata,[{""}]}];
sheet1_a38_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ISODD"},read_from_excel_data(Config,{"Sheet1",37,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",37,0}), {string,"ISODD"}).
  
sheet1_a22_test(doc) -> [{userdata,[{""}]}];
sheet1_a22_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,-2146826246},read_from_excel_data(Config,{"Sheet1",21,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",21,0}), {number,-2146826246}).
  
sheet1_a33_test(doc) -> [{userdata,[{""}]}];
sheet1_a33_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ISEVEN"},read_from_excel_data(Config,{"Sheet1",32,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",32,0}), {string,"ISEVEN"}).
  
sheet1_a44_test(doc) -> [{userdata,[{""}]}];
sheet1_a44_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Total"},read_from_excel_data(Config,{"Sheet1",43,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",43,0}), {string,"Total"}).
  
sheet1_a28_test(doc) -> [{userdata,[{""}]}];
sheet1_a28_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ERROR.TYPE"},read_from_excel_data(Config,{"Sheet1",27,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",27,0}), {string,"ERROR.TYPE"}).
  
sheet1_a39_test(doc) -> [{userdata,[{""}]}];
sheet1_a39_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ISREF"},read_from_excel_data(Config,{"Sheet1",38,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",38,0}), {string,"ISREF"}).
  
sheet1_a1_test(doc) -> [{userdata,[{""}]}];
sheet1_a1_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"INFORMATION FUNCTIONS"},read_from_excel_data(Config,{"Sheet1",0,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",0,0}), {string,"INFORMATION FUNCTIONS"}).
  
sheet1_a12_test(doc) -> [{userdata,[{""}]}];
sheet1_a12_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,0.0225},read_from_excel_data(Config,{"Sheet1",11,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",11,0}), {number,0.0225}).
  
sheet1_a34_test(doc) -> [{userdata,[{""}]}];
sheet1_a34_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ISLOGICAL"},read_from_excel_data(Config,{"Sheet1",33,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",33,0}), {string,"ISLOGICAL"}).
  
sheet1_a7_test(doc) -> [{userdata,[{""}]}];
sheet1_a7_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"#Succeded"},read_from_excel_data(Config,{"Sheet1",6,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",6,0}), {string,"#Succeded"}).
  
sheet1_a18_test(doc) -> [{userdata,[{""}]}];
sheet1_a18_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,12.8},read_from_excel_data(Config,{"Sheet1",17,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",17,0}), {number,12.8}).
  
sheet1_a29_test(doc) -> [{userdata,[{""}]}];
sheet1_a29_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"INFO"},read_from_excel_data(Config,{"Sheet1",28,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",28,0}), {string,"INFO"}).
  
sheet1_a40_test(doc) -> [{userdata,[{""}]}];
sheet1_a40_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ISTEXT"},read_from_excel_data(Config,{"Sheet1",39,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",39,0}), {string,"ISTEXT"}).
  
sheet1_a13_test(doc) -> [{userdata,[{""}]}];
sheet1_a13_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"1999/11/11 00:00:00"},read_from_excel_data(Config,{"Sheet1",12,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",12,0}), {string,"1999/11/11 00:00:00"}).
  
sheet1_a35_test(doc) -> [{userdata,[{""}]}];
sheet1_a35_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ISNA"},read_from_excel_data(Config,{"Sheet1",34,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",34,0}), {string,"ISNA"}).
  
sheet1_a8_test(doc) -> [{userdata,[{""}]}];
sheet1_a8_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=SUM(H26:H43)"},read_from_excel_data(Config,{"Sheet1",7,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",7,0}), {formula,"=SUM(H26:H43)"}).
  
sheet1_a19_test(doc) -> [{userdata,[{""}]}];
sheet1_a19_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=233/0"},read_from_excel_data(Config,{"Sheet1",18,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",18,0}), {formula,"=233/0"}).
  
sheet1_a30_test(doc) -> [{userdata,[{""}]}];
sheet1_a30_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ISBLANK"},read_from_excel_data(Config,{"Sheet1",29,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",29,0}), {string,"ISBLANK"}).
  
sheet1_a41_test(doc) -> [{userdata,[{""}]}];
sheet1_a41_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"N"},read_from_excel_data(Config,{"Sheet1",40,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",40,0}), {string,"N"}).
  
sheet1_a3_test(doc) -> [{userdata,[{""}]}];
sheet1_a3_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Test Status"},read_from_excel_data(Config,{"Sheet1",2,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",2,0}), {string,"Test Status"}).
  
sheet1_a14_test(doc) -> [{userdata,[{""}]}];
sheet1_a14_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,232323.0},read_from_excel_data(Config,{"Sheet1",13,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",13,0}), {number,232323.0}).
  
sheet1_a25_test(doc) -> [{userdata,[{""}]}];
sheet1_a25_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Function"},read_from_excel_data(Config,{"Sheet1",24,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",24,0}), {string,"Function"}).
  
sheet1_a36_test(doc) -> [{userdata,[{""}]}];
sheet1_a36_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ISNONTEXT"},read_from_excel_data(Config,{"Sheet1",35,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",35,0}), {string,"ISNONTEXT"}).
  
sheet1_a20_test(doc) -> [{userdata,[{""}]}];
sheet1_a20_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=NORMSINV(1.2)"},read_from_excel_data(Config,{"Sheet1",19,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",19,0}), {formula,"=NORMSINV(1.2)"}).
  
sheet1_a31_test(doc) -> [{userdata,[{""}]}];
sheet1_a31_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ISERR"},read_from_excel_data(Config,{"Sheet1",30,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",30,0}), {string,"ISERR"}).
  
sheet1_a42_test(doc) -> [{userdata,[{""}]}];
sheet1_a42_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"NA"},read_from_excel_data(Config,{"Sheet1",41,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",41,0}), {string,"NA"}).
  
sheet1_a4_test(doc) -> [{userdata,[{""}]}];
sheet1_a4_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(A8=B8,\"All ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",3,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",3,0}), {formula,"=IF(A8=B8,\"All ok.\",\"FAILED!!\")"}).
  
sheet1_a26_test(doc) -> [{userdata,[{""}]}];
sheet1_a26_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"CELL"},read_from_excel_data(Config,{"Sheet1",25,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",25,0}), {string,"CELL"}).
  
sheet1_a37_test(doc) -> [{userdata,[{""}]}];
sheet1_a37_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ISNUMBER"},read_from_excel_data(Config,{"Sheet1",36,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",36,0}), {string,"ISNUMBER"}).
  
sheet1_a10_test(doc) -> [{userdata,[{""}]}];
sheet1_a10_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Test data"},read_from_excel_data(Config,{"Sheet1",9,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",9,0}), {string,"Test data"}).
  
sheet1_a21_test(doc) -> [{userdata,[{""}]}];
sheet1_a21_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=FACT(\"jack\")"},read_from_excel_data(Config,{"Sheet1",20,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",20,0}), {formula,"=FACT(\"jack\")"}).
  
sheet1_a32_test(doc) -> [{userdata,[{""}]}];
sheet1_a32_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"ISERROR"},read_from_excel_data(Config,{"Sheet1",31,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",31,0}), {string,"ISERROR"}).
  
sheet1_a43_test(doc) -> [{userdata,[{""}]}];
sheet1_a43_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"TYPE"},read_from_excel_data(Config,{"Sheet1",42,0})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",42,0}), {string,"TYPE"}).
  
sheet1_b27_test(doc) -> [{userdata,[{""}]}];
sheet1_b27_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=COUNTBLANK(A12:A18)"},read_from_excel_data(Config,{"Sheet1",26,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",26,1}), {formula,"=COUNTBLANK(A12:A18)"}).
  
sheet1_b38_test(doc) -> [{userdata,[{""}]}];
sheet1_b38_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISODD(3)"},read_from_excel_data(Config,{"Sheet1",37,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",37,1}), {formula,"=ISODD(3)"}).
  
sheet1_b33_test(doc) -> [{userdata,[{""}]}];
sheet1_b33_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISEVEN(3)"},read_from_excel_data(Config,{"Sheet1",32,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",32,1}), {formula,"=ISEVEN(3)"}).
  
sheet1_b28_test(doc) -> [{userdata,[{""}]}];
sheet1_b28_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ERROR.TYPE(A19)"},read_from_excel_data(Config,{"Sheet1",27,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",27,1}), {formula,"=ERROR.TYPE(A19)"}).
  
sheet1_b39_test(doc) -> [{userdata,[{""}]}];
sheet1_b39_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISREF(4)"},read_from_excel_data(Config,{"Sheet1",38,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",38,1}), {formula,"=ISREF(4)"}).
  
sheet1_b12_test(doc) -> [{userdata,[{""}]}];
sheet1_b12_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,1.0},read_from_excel_data(Config,{"Sheet1",11,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",11,1}), {number,1.0}).
  
sheet1_b34_test(doc) -> [{userdata,[{""}]}];
sheet1_b34_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISLOGICAL(B12)"},read_from_excel_data(Config,{"Sheet1",33,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",33,1}), {formula,"=ISLOGICAL(B12)"}).
  
sheet1_b7_test(doc) -> [{userdata,[{""}]}];
sheet1_b7_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"#Total"},read_from_excel_data(Config,{"Sheet1",6,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",6,1}), {string,"#Total"}).
  
sheet1_b29_test(doc) -> [{userdata,[{""}]}];
sheet1_b29_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=INFO(\"system\")"},read_from_excel_data(Config,{"Sheet1",28,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",28,1}), {formula,"=INFO(\"system\")"}).
  
sheet1_b40_test(doc) -> [{userdata,[{""}]}];
sheet1_b40_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISTEXT(B13)"},read_from_excel_data(Config,{"Sheet1",39,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",39,1}), {formula,"=ISTEXT(B13)"}).
  
sheet1_b13_test(doc) -> [{userdata,[{""}]}];
sheet1_b13_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"koe"},read_from_excel_data(Config,{"Sheet1",12,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",12,1}), {string,"koe"}).
  
sheet1_b35_test(doc) -> [{userdata,[{""}]}];
sheet1_b35_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISNA(B19)"},read_from_excel_data(Config,{"Sheet1",34,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",34,1}), {formula,"=ISNA(B19)"}).
  
sheet1_b8_test(doc) -> [{userdata,[{""}]}];
sheet1_b8_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,18.0},read_from_excel_data(Config,{"Sheet1",7,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",7,1}), {number,18.0}).
  
sheet1_b30_test(doc) -> [{userdata,[{""}]}];
sheet1_b30_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISBLANK(A12)"},read_from_excel_data(Config,{"Sheet1",29,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",29,1}), {formula,"=ISBLANK(A12)"}).
  
sheet1_b41_test(doc) -> [{userdata,[{""}]}];
sheet1_b41_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=N(A18)"},read_from_excel_data(Config,{"Sheet1",40,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",40,1}), {formula,"=N(A18)"}).
  
sheet1_b25_test(doc) -> [{userdata,[{""}]}];
sheet1_b25_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"1st test"},read_from_excel_data(Config,{"Sheet1",24,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",24,1}), {string,"1st test"}).
  
sheet1_b36_test(doc) -> [{userdata,[{""}]}];
sheet1_b36_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISNONTEXT(B13)"},read_from_excel_data(Config,{"Sheet1",35,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",35,1}), {formula,"=ISNONTEXT(B13)"}).
  
sheet1_b31_test(doc) -> [{userdata,[{""}]}];
sheet1_b31_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISERR(A22)"},read_from_excel_data(Config,{"Sheet1",30,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",30,1}), {formula,"=ISERR(A22)"}).
  
sheet1_b42_test(doc) -> [{userdata,[{""}]}];
sheet1_b42_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=NA()"},read_from_excel_data(Config,{"Sheet1",41,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",41,1}), {formula,"=NA()"}).
  
sheet1_b26_test(doc) -> [{userdata,[{""}]}];
sheet1_b26_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CELL(\"format\",A12)"},read_from_excel_data(Config,{"Sheet1",25,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",25,1}), {formula,"=CELL(\"format\",A12)"}).
  
sheet1_b37_test(doc) -> [{userdata,[{""}]}];
sheet1_b37_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISNUMBER(A16)"},read_from_excel_data(Config,{"Sheet1",36,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",36,1}), {formula,"=ISNUMBER(A16)"}).
  
sheet1_b32_test(doc) -> [{userdata,[{""}]}];
sheet1_b32_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISERROR(A19)"},read_from_excel_data(Config,{"Sheet1",31,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",31,1}), {formula,"=ISERROR(A19)"}).
  
sheet1_b43_test(doc) -> [{userdata,[{""}]}];
sheet1_b43_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=TYPE(A22)"},read_from_excel_data(Config,{"Sheet1",42,1})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",42,1}), {formula,"=TYPE(A22)"}).
  
sheet1_c27_test(doc) -> [{userdata,[{""}]}];
sheet1_c27_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,2.0},read_from_excel_data(Config,{"Sheet1",26,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",26,2}), {number,2.0}).
  
sheet1_c38_test(doc) -> [{userdata,[{""}]}];
sheet1_c38_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",37,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",37,2}), {boolean,true}).
  
sheet1_c33_test(doc) -> [{userdata,[{""}]}];
sheet1_c33_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",32,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",32,2}), {boolean,false}).
  
sheet1_c28_test(doc) -> [{userdata,[{""}]}];
sheet1_c28_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,2.0},read_from_excel_data(Config,{"Sheet1",27,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",27,2}), {number,2.0}).
  
sheet1_c39_test(doc) -> [{userdata,[{""}]}];
sheet1_c39_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",38,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",38,2}), {boolean,false}).
  
sheet1_c34_test(doc) -> [{userdata,[{""}]}];
sheet1_c34_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",33,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",33,2}), {boolean,false}).
  
sheet1_c29_test(doc) -> [{userdata,[{""}]}];
sheet1_c29_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"pcdos"},read_from_excel_data(Config,{"Sheet1",28,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",28,2}), {string,"pcdos"}).
  
sheet1_c40_test(doc) -> [{userdata,[{""}]}];
sheet1_c40_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",39,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",39,2}), {boolean,true}).
  
sheet1_c35_test(doc) -> [{userdata,[{""}]}];
sheet1_c35_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",34,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",34,2}), {boolean,false}).
  
sheet1_c30_test(doc) -> [{userdata,[{""}]}];
sheet1_c30_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",29,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",29,2}), {boolean,false}).
  
sheet1_c41_test(doc) -> [{userdata,[{""}]}];
sheet1_c41_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,12.8},read_from_excel_data(Config,{"Sheet1",40,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",40,2}), {number,12.8}).
  
sheet1_c25_test(doc) -> [{userdata,[{""}]}];
sheet1_c25_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Correct"},read_from_excel_data(Config,{"Sheet1",24,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",24,2}), {string,"Correct"}).
  
sheet1_c36_test(doc) -> [{userdata,[{""}]}];
sheet1_c36_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",35,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",35,2}), {boolean,false}).
  
sheet1_c31_test(doc) -> [{userdata,[{""}]}];
sheet1_c31_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",30,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",30,2}), {boolean,false}).
  
sheet1_c42_test(doc) -> [{userdata,[{""}]}];
sheet1_c42_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,0.0},read_from_excel_data(Config,{"Sheet1",41,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",41,2}), {number,0.0}).
  
sheet1_c26_test(doc) -> [{userdata,[{""}]}];
sheet1_c26_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"P2"},read_from_excel_data(Config,{"Sheet1",25,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",25,2}), {string,"P2"}).
  
sheet1_c37_test(doc) -> [{userdata,[{""}]}];
sheet1_c37_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",36,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",36,2}), {boolean,true}).
  
sheet1_c32_test(doc) -> [{userdata,[{""}]}];
sheet1_c32_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",31,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",31,2}), {boolean,true}).
  
sheet1_c43_test(doc) -> [{userdata,[{""}]}];
sheet1_c43_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,16.0},read_from_excel_data(Config,{"Sheet1",42,2})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",42,2}), {number,16.0}).
  
sheet1_d27_test(doc) -> [{userdata,[{""}]}];
sheet1_d27_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=COUNTBLANK(A12:A19)"},read_from_excel_data(Config,{"Sheet1",26,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",26,3}), {formula,"=COUNTBLANK(A12:A19)"}).
  
sheet1_d38_test(doc) -> [{userdata,[{""}]}];
sheet1_d38_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISODD(-2)"},read_from_excel_data(Config,{"Sheet1",37,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",37,3}), {formula,"=ISODD(-2)"}).
  
sheet1_d33_test(doc) -> [{userdata,[{""}]}];
sheet1_d33_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISEVEN(2)"},read_from_excel_data(Config,{"Sheet1",32,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",32,3}), {formula,"=ISEVEN(2)"}).
  
sheet1_d28_test(doc) -> [{userdata,[{""}]}];
sheet1_d28_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ERROR.TYPE(A20)"},read_from_excel_data(Config,{"Sheet1",27,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",27,3}), {formula,"=ERROR.TYPE(A20)"}).
  
sheet1_d39_test(doc) -> [{userdata,[{""}]}];
sheet1_d39_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISREF(A2)"},read_from_excel_data(Config,{"Sheet1",38,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",38,3}), {formula,"=ISREF(A2)"}).
  
sheet1_d34_test(doc) -> [{userdata,[{""}]}];
sheet1_d34_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISLOGICAL(A19)"},read_from_excel_data(Config,{"Sheet1",33,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",33,3}), {formula,"=ISLOGICAL(A19)"}).
  
sheet1_d29_test(doc) -> [{userdata,[{""}]}];
sheet1_d29_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=INFO(\"release\")"},read_from_excel_data(Config,{"Sheet1",28,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",28,3}), {formula,"=INFO(\"release\")"}).
  
sheet1_d40_test(doc) -> [{userdata,[{""}]}];
sheet1_d40_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISTEXT(A19)"},read_from_excel_data(Config,{"Sheet1",39,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",39,3}), {formula,"=ISTEXT(A19)"}).
  
sheet1_d35_test(doc) -> [{userdata,[{""}]}];
sheet1_d35_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISNA(A21)"},read_from_excel_data(Config,{"Sheet1",34,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",34,3}), {formula,"=ISNA(A21)"}).
  
sheet1_d30_test(doc) -> [{userdata,[{""}]}];
sheet1_d30_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISBLANK(A15)"},read_from_excel_data(Config,{"Sheet1",29,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",29,3}), {formula,"=ISBLANK(A15)"}).
  
sheet1_d41_test(doc) -> [{userdata,[{""}]}];
sheet1_d41_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=N(B13)"},read_from_excel_data(Config,{"Sheet1",40,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",40,3}), {formula,"=N(B13)"}).
  
sheet1_d25_test(doc) -> [{userdata,[{""}]}];
sheet1_d25_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"2nd test"},read_from_excel_data(Config,{"Sheet1",24,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",24,3}), {string,"2nd test"}).
  
sheet1_d36_test(doc) -> [{userdata,[{""}]}];
sheet1_d36_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISNONTEXT(A14)"},read_from_excel_data(Config,{"Sheet1",35,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",35,3}), {formula,"=ISNONTEXT(A14)"}).
  
sheet1_d31_test(doc) -> [{userdata,[{""}]}];
sheet1_d31_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISERR(A21)"},read_from_excel_data(Config,{"Sheet1",30,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",30,3}), {formula,"=ISERR(A21)"}).
  
sheet1_d42_test(doc) -> [{userdata,[{""}]}];
sheet1_d42_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,0.0},read_from_excel_data(Config,{"Sheet1",41,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",41,3}), {number,0.0}).
  
sheet1_d26_test(doc) -> [{userdata,[{""}]}];
sheet1_d26_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CELL(\"format\",A13)"},read_from_excel_data(Config,{"Sheet1",25,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",25,3}), {formula,"=CELL(\"format\",A13)"}).
  
sheet1_d37_test(doc) -> [{userdata,[{""}]}];
sheet1_d37_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISNUMBER(A14)"},read_from_excel_data(Config,{"Sheet1",36,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",36,3}), {formula,"=ISNUMBER(A14)"}).
  
sheet1_d32_test(doc) -> [{userdata,[{""}]}];
sheet1_d32_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISERROR(A22)"},read_from_excel_data(Config,{"Sheet1",31,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",31,3}), {formula,"=ISERROR(A22)"}).
  
sheet1_d43_test(doc) -> [{userdata,[{""}]}];
sheet1_d43_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=TYPE(B13)"},read_from_excel_data(Config,{"Sheet1",42,3})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",42,3}), {formula,"=TYPE(B13)"}).
  
sheet1_e27_test(doc) -> [{userdata,[{""}]}];
sheet1_e27_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,2.0},read_from_excel_data(Config,{"Sheet1",26,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",26,4}), {number,2.0}).
  
sheet1_e38_test(doc) -> [{userdata,[{""}]}];
sheet1_e38_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",37,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",37,4}), {boolean,false}).
  
sheet1_e33_test(doc) -> [{userdata,[{""}]}];
sheet1_e33_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",32,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",32,4}), {boolean,true}).
  
sheet1_e28_test(doc) -> [{userdata,[{""}]}];
sheet1_e28_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,6.0},read_from_excel_data(Config,{"Sheet1",27,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",27,4}), {number,6.0}).
  
sheet1_e39_test(doc) -> [{userdata,[{""}]}];
sheet1_e39_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",38,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",38,4}), {boolean,true}).
  
sheet1_e34_test(doc) -> [{userdata,[{""}]}];
sheet1_e34_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",33,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",33,4}), {boolean,false}).
  
sheet1_e29_test(doc) -> [{userdata,[{""}]}];
sheet1_e29_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"9.0"},read_from_excel_data(Config,{"Sheet1",28,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",28,4}), {string,"9.0"}).
  
sheet1_e40_test(doc) -> [{userdata,[{""}]}];
sheet1_e40_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",39,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",39,4}), {boolean,false}).
  
sheet1_e35_test(doc) -> [{userdata,[{""}]}];
sheet1_e35_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",34,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",34,4}), {boolean,false}).
  
sheet1_e30_test(doc) -> [{userdata,[{""}]}];
sheet1_e30_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",29,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",29,4}), {boolean,true}).
  
sheet1_e41_test(doc) -> [{userdata,[{""}]}];
sheet1_e41_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,0.0},read_from_excel_data(Config,{"Sheet1",40,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",40,4}), {number,0.0}).
  
sheet1_e25_test(doc) -> [{userdata,[{""}]}];
sheet1_e25_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Correct"},read_from_excel_data(Config,{"Sheet1",24,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",24,4}), {string,"Correct"}).
  
sheet1_e36_test(doc) -> [{userdata,[{""}]}];
sheet1_e36_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",35,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",35,4}), {boolean,true}).
  
sheet1_e31_test(doc) -> [{userdata,[{""}]}];
sheet1_e31_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",30,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",30,4}), {boolean,true}).
  
sheet1_e42_test(doc) -> [{userdata,[{""}]}];
sheet1_e42_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,0.0},read_from_excel_data(Config,{"Sheet1",41,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",41,4}), {number,0.0}).
  
sheet1_e26_test(doc) -> [{userdata,[{""}]}];
sheet1_e26_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"D2"},read_from_excel_data(Config,{"Sheet1",25,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",25,4}), {string,"D2"}).
  
sheet1_e37_test(doc) -> [{userdata,[{""}]}];
sheet1_e37_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",36,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",36,4}), {boolean,true}).
  
sheet1_e32_test(doc) -> [{userdata,[{""}]}];
sheet1_e32_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",31,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",31,4}), {boolean,true}).
  
sheet1_e43_test(doc) -> [{userdata,[{""}]}];
sheet1_e43_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,2.0},read_from_excel_data(Config,{"Sheet1",42,4})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",42,4}), {number,2.0}).
  
sheet1_f27_test(doc) -> [{userdata,[{""}]}];
sheet1_f27_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=COUNTBLANK(A14)"},read_from_excel_data(Config,{"Sheet1",26,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",26,5}), {formula,"=COUNTBLANK(A14)"}).
  
sheet1_f38_test(doc) -> [{userdata,[{""}]}];
sheet1_f38_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISODD(5)"},read_from_excel_data(Config,{"Sheet1",37,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",37,5}), {formula,"=ISODD(5)"}).
  
sheet1_f33_test(doc) -> [{userdata,[{""}]}];
sheet1_f33_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISEVEN(2.2)"},read_from_excel_data(Config,{"Sheet1",32,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",32,5}), {formula,"=ISEVEN(2.2)"}).
  
sheet1_f28_test(doc) -> [{userdata,[{""}]}];
sheet1_f28_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ERROR.TYPE(A21)"},read_from_excel_data(Config,{"Sheet1",27,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",27,5}), {formula,"=ERROR.TYPE(A21)"}).
  
sheet1_f39_test(doc) -> [{userdata,[{""}]}];
sheet1_f39_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISREF(A20)"},read_from_excel_data(Config,{"Sheet1",38,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",38,5}), {formula,"=ISREF(A20)"}).
  
sheet1_f34_test(doc) -> [{userdata,[{""}]}];
sheet1_f34_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISLOGICAL(C30)"},read_from_excel_data(Config,{"Sheet1",33,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",33,5}), {formula,"=ISLOGICAL(C30)"}).
  
sheet1_f29_test(doc) -> [{userdata,[{""}]}];
sheet1_f29_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=INFO(\"osversion\")"},read_from_excel_data(Config,{"Sheet1",28,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",28,5}), {formula,"=INFO(\"osversion\")"}).
  
sheet1_f40_test(doc) -> [{userdata,[{""}]}];
sheet1_f40_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISTEXT(A18)"},read_from_excel_data(Config,{"Sheet1",39,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",39,5}), {formula,"=ISTEXT(A18)"}).
  
sheet1_f35_test(doc) -> [{userdata,[{""}]}];
sheet1_f35_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISNA(A22)"},read_from_excel_data(Config,{"Sheet1",34,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",34,5}), {formula,"=ISNA(A22)"}).
  
sheet1_f30_test(doc) -> [{userdata,[{""}]}];
sheet1_f30_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISBLANK(A19)"},read_from_excel_data(Config,{"Sheet1",29,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",29,5}), {formula,"=ISBLANK(A19)"}).
  
sheet1_f41_test(doc) -> [{userdata,[{""}]}];
sheet1_f41_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=N(B32)"},read_from_excel_data(Config,{"Sheet1",40,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",40,5}), {formula,"=N(B32)"}).
  
sheet1_f25_test(doc) -> [{userdata,[{""}]}];
sheet1_f25_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"3rd test"},read_from_excel_data(Config,{"Sheet1",24,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",24,5}), {string,"3rd test"}).
  
sheet1_f36_test(doc) -> [{userdata,[{""}]}];
sheet1_f36_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISNONTEXT(A19)"},read_from_excel_data(Config,{"Sheet1",35,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",35,5}), {formula,"=ISNONTEXT(A19)"}).
  
sheet1_f31_test(doc) -> [{userdata,[{""}]}];
sheet1_f31_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISERR(A14)"},read_from_excel_data(Config,{"Sheet1",30,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",30,5}), {formula,"=ISERR(A14)"}).
  
sheet1_f42_test(doc) -> [{userdata,[{""}]}];
sheet1_f42_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,0.0},read_from_excel_data(Config,{"Sheet1",41,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",41,5}), {number,0.0}).
  
sheet1_f26_test(doc) -> [{userdata,[{""}]}];
sheet1_f26_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=CELL(\"format\",A14)"},read_from_excel_data(Config,{"Sheet1",25,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",25,5}), {formula,"=CELL(\"format\",A14)"}).
  
sheet1_f37_test(doc) -> [{userdata,[{""}]}];
sheet1_f37_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISNUMBER(B13)"},read_from_excel_data(Config,{"Sheet1",36,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",36,5}), {formula,"=ISNUMBER(B13)"}).
  
sheet1_f32_test(doc) -> [{userdata,[{""}]}];
sheet1_f32_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=ISERROR(A13)"},read_from_excel_data(Config,{"Sheet1",31,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",31,5}), {formula,"=ISERROR(A13)"}).
  
sheet1_f43_test(doc) -> [{userdata,[{""}]}];
sheet1_f43_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=TYPE(A14)"},read_from_excel_data(Config,{"Sheet1",42,5})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",42,5}), {formula,"=TYPE(A14)"}).
  
sheet1_g27_test(doc) -> [{userdata,[{""}]}];
sheet1_g27_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,0.0},read_from_excel_data(Config,{"Sheet1",26,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",26,6}), {number,0.0}).
  
sheet1_g38_test(doc) -> [{userdata,[{""}]}];
sheet1_g38_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",37,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",37,6}), {boolean,true}).
  
sheet1_g33_test(doc) -> [{userdata,[{""}]}];
sheet1_g33_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",32,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",32,6}), {boolean,true}).
  
sheet1_g28_test(doc) -> [{userdata,[{""}]}];
sheet1_g28_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,3.0},read_from_excel_data(Config,{"Sheet1",27,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",27,6}), {number,3.0}).
  
sheet1_g39_test(doc) -> [{userdata,[{""}]}];
sheet1_g39_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",38,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",38,6}), {boolean,true}).
  
sheet1_g34_test(doc) -> [{userdata,[{""}]}];
sheet1_g34_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",33,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",33,6}), {boolean,true}).
  
sheet1_g29_test(doc) -> [{userdata,[{""}]}];
sheet1_g29_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Windows (32-bit) 4.00"},read_from_excel_data(Config,{"Sheet1",28,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",28,6}), {string,"Windows (32-bit) 4.00"}).
  
sheet1_g40_test(doc) -> [{userdata,[{""}]}];
sheet1_g40_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",39,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",39,6}), {boolean,false}).
  
sheet1_g35_test(doc) -> [{userdata,[{""}]}];
sheet1_g35_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",34,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",34,6}), {boolean,true}).
  
sheet1_g30_test(doc) -> [{userdata,[{""}]}];
sheet1_g30_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",29,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",29,6}), {boolean,false}).
  
sheet1_g41_test(doc) -> [{userdata,[{""}]}];
sheet1_g41_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,1.0},read_from_excel_data(Config,{"Sheet1",40,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",40,6}), {number,1.0}).
  
sheet1_g25_test(doc) -> [{userdata,[{""}]}];
sheet1_g25_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Correct"},read_from_excel_data(Config,{"Sheet1",24,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",24,6}), {string,"Correct"}).
  
sheet1_g36_test(doc) -> [{userdata,[{""}]}];
sheet1_g36_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,true},read_from_excel_data(Config,{"Sheet1",35,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",35,6}), {boolean,true}).
  
sheet1_g31_test(doc) -> [{userdata,[{""}]}];
sheet1_g31_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",30,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",30,6}), {boolean,false}).
  
sheet1_g42_test(doc) -> [{userdata,[{""}]}];
sheet1_g42_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,0.0},read_from_excel_data(Config,{"Sheet1",41,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",41,6}), {number,0.0}).
  
sheet1_g26_test(doc) -> [{userdata,[{""}]}];
sheet1_g26_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"C0-"},read_from_excel_data(Config,{"Sheet1",25,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",25,6}), {string,"C0-"}).
  
sheet1_g37_test(doc) -> [{userdata,[{""}]}];
sheet1_g37_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",36,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",36,6}), {boolean,false}).
  
sheet1_g32_test(doc) -> [{userdata,[{""}]}];
sheet1_g32_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{boolean,false},read_from_excel_data(Config,{"Sheet1",31,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",31,6}), {boolean,false}).
  
sheet1_g43_test(doc) -> [{userdata,[{""}]}];
sheet1_g43_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,1.0},read_from_excel_data(Config,{"Sheet1",42,6})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",42,6}), {number,1.0}).
  
sheet1_h27_test(doc) -> [{userdata,[{""}]}];
sheet1_h27_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B27=C27,D27=E27,F27=G27),1,0)"},read_from_excel_data(Config,{"Sheet1",26,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",26,7}), {formula,"=IF(AND(B27=C27,D27=E27,F27=G27),1,0)"}).
  
sheet1_h38_test(doc) -> [{userdata,[{""}]}];
sheet1_h38_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B38=C38,D38=E38,F38=G38),1,0)"},read_from_excel_data(Config,{"Sheet1",37,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",37,7}), {formula,"=IF(AND(B38=C38,D38=E38,F38=G38),1,0)"}).
  
sheet1_h33_test(doc) -> [{userdata,[{""}]}];
sheet1_h33_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B33=C33,D33=E33,F33=G33),1,0)"},read_from_excel_data(Config,{"Sheet1",32,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",32,7}), {formula,"=IF(AND(B33=C33,D33=E33,F33=G33),1,0)"}).
  
sheet1_h28_test(doc) -> [{userdata,[{""}]}];
sheet1_h28_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B28=C28,D28=E28,F28=G28),1,0)"},read_from_excel_data(Config,{"Sheet1",27,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",27,7}), {formula,"=IF(AND(B28=C28,D28=E28,F28=G28),1,0)"}).
  
sheet1_h39_test(doc) -> [{userdata,[{""}]}];
sheet1_h39_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B39=C39,D39=E39,F39=G39),1,0)"},read_from_excel_data(Config,{"Sheet1",38,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",38,7}), {formula,"=IF(AND(B39=C39,D39=E39,F39=G39),1,0)"}).
  
sheet1_h34_test(doc) -> [{userdata,[{""}]}];
sheet1_h34_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B34=C34,D34=E34,F34=G34),1,0)"},read_from_excel_data(Config,{"Sheet1",33,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",33,7}), {formula,"=IF(AND(B34=C34,D34=E34,F34=G34),1,0)"}).
  
sheet1_h29_test(doc) -> [{userdata,[{""}]}];
sheet1_h29_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{number,1.0},read_from_excel_data(Config,{"Sheet1",28,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",28,7}), {number,1.0}).
  
sheet1_h40_test(doc) -> [{userdata,[{""}]}];
sheet1_h40_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B40=C40,D40=E40,F40=G40),1,0)"},read_from_excel_data(Config,{"Sheet1",39,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",39,7}), {formula,"=IF(AND(B40=C40,D40=E40,F40=G40),1,0)"}).
  
sheet1_h35_test(doc) -> [{userdata,[{""}]}];
sheet1_h35_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B35=C35,D35=E35,F35=G35),1,0)"},read_from_excel_data(Config,{"Sheet1",34,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",34,7}), {formula,"=IF(AND(B35=C35,D35=E35,F35=G35),1,0)"}).
  
sheet1_h30_test(doc) -> [{userdata,[{""}]}];
sheet1_h30_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B30=C30,D30=E30,F30=G30),1,0)"},read_from_excel_data(Config,{"Sheet1",29,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",29,7}), {formula,"=IF(AND(B30=C30,D30=E30,F30=G30),1,0)"}).
  
sheet1_h41_test(doc) -> [{userdata,[{""}]}];
sheet1_h41_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B41=C41,D41=E41,F41=G41),1,0)"},read_from_excel_data(Config,{"Sheet1",40,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",40,7}), {formula,"=IF(AND(B41=C41,D41=E41,F41=G41),1,0)"}).
  
sheet1_h25_test(doc) -> [{userdata,[{""}]}];
sheet1_h25_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Status"},read_from_excel_data(Config,{"Sheet1",24,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",24,7}), {string,"Status"}).
  
sheet1_h36_test(doc) -> [{userdata,[{""}]}];
sheet1_h36_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B36=C36,D36=E36,F36=G36),1,0)"},read_from_excel_data(Config,{"Sheet1",35,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",35,7}), {formula,"=IF(AND(B36=C36,D36=E36,F36=G36),1,0)"}).
  
sheet1_h31_test(doc) -> [{userdata,[{""}]}];
sheet1_h31_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B31=C31,D31=E31,F31=G31),1,0)"},read_from_excel_data(Config,{"Sheet1",30,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",30,7}), {formula,"=IF(AND(B31=C31,D31=E31,F31=G31),1,0)"}).
  
sheet1_h42_test(doc) -> [{userdata,[{""}]}];
sheet1_h42_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(ERROR.TYPE(B42)=7,1,0)"},read_from_excel_data(Config,{"Sheet1",41,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",41,7}), {formula,"=IF(ERROR.TYPE(B42)=7,1,0)"}).
  
sheet1_h26_test(doc) -> [{userdata,[{""}]}];
sheet1_h26_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B26=C26,D26=E26,F26=G26),1,0)"},read_from_excel_data(Config,{"Sheet1",25,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",25,7}), {formula,"=IF(AND(B26=C26,D26=E26,F26=G26),1,0)"}).
  
sheet1_h37_test(doc) -> [{userdata,[{""}]}];
sheet1_h37_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B37=C37,D37=E37,F37=G37),1,0)"},read_from_excel_data(Config,{"Sheet1",36,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",36,7}), {formula,"=IF(AND(B37=C37,D37=E37,F37=G37),1,0)"}).
  
sheet1_h32_test(doc) -> [{userdata,[{""}]}];
sheet1_h32_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B32=C32,D32=E32,F32=G32),1,0)"},read_from_excel_data(Config,{"Sheet1",31,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",31,7}), {formula,"=IF(AND(B32=C32,D32=E32,F32=G32),1,0)"}).
  
sheet1_h43_test(doc) -> [{userdata,[{""}]}];
sheet1_h43_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(AND(B43=C43,D43=E43,F43=G43),1,0)"},read_from_excel_data(Config,{"Sheet1",42,7})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",42,7}), {formula,"=IF(AND(B43=C43,D43=E43,F43=G43),1,0)"}).
  
sheet1_i27_test(doc) -> [{userdata,[{""}]}];
sheet1_i27_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H27,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",26,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",26,8}), {formula,"=IF(H27,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i38_test(doc) -> [{userdata,[{""}]}];
sheet1_i38_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H38,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",37,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",37,8}), {formula,"=IF(H38,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i33_test(doc) -> [{userdata,[{""}]}];
sheet1_i33_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H33,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",32,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",32,8}), {formula,"=IF(H33,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i28_test(doc) -> [{userdata,[{""}]}];
sheet1_i28_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H28,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",27,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",27,8}), {formula,"=IF(H28,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i39_test(doc) -> [{userdata,[{""}]}];
sheet1_i39_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H39,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",38,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",38,8}), {formula,"=IF(H39,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i34_test(doc) -> [{userdata,[{""}]}];
sheet1_i34_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H34,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",33,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",33,8}), {formula,"=IF(H34,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i29_test(doc) -> [{userdata,[{""}]}];
sheet1_i29_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H29,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",28,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",28,8}), {formula,"=IF(H29,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i40_test(doc) -> [{userdata,[{""}]}];
sheet1_i40_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H40,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",39,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",39,8}), {formula,"=IF(H40,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i35_test(doc) -> [{userdata,[{""}]}];
sheet1_i35_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H35,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",34,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",34,8}), {formula,"=IF(H35,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i30_test(doc) -> [{userdata,[{""}]}];
sheet1_i30_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H30,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",29,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",29,8}), {formula,"=IF(H30,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i41_test(doc) -> [{userdata,[{""}]}];
sheet1_i41_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H41,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",40,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",40,8}), {formula,"=IF(H41,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i25_test(doc) -> [{userdata,[{""}]}];
sheet1_i25_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{string,"Status message"},read_from_excel_data(Config,{"Sheet1",24,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",24,8}), {string,"Status message"}).
  
sheet1_i36_test(doc) -> [{userdata,[{""}]}];
sheet1_i36_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H36,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",35,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",35,8}), {formula,"=IF(H36,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i31_test(doc) -> [{userdata,[{""}]}];
sheet1_i31_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H31,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",30,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",30,8}), {formula,"=IF(H31,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i42_test(doc) -> [{userdata,[{""}]}];
sheet1_i42_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H42,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",41,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",41,8}), {formula,"=IF(H42,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i26_test(doc) -> [{userdata,[{""}]}];
sheet1_i26_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H26,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",25,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",25,8}), {formula,"=IF(H26,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i37_test(doc) -> [{userdata,[{""}]}];
sheet1_i37_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H37,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",36,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",36,8}), {formula,"=IF(H37,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i32_test(doc) -> [{userdata,[{""}]}];
sheet1_i32_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H32,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",31,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",31,8}), {formula,"=IF(H32,\"Ok.\",\"FAILED!!\")"}).
  
sheet1_i43_test(doc) -> [{userdata,[{""}]}];
sheet1_i43_test(Config) -> 
  io:format("Expected : ~p~nGot      : ~p~n",[{formula,"=IF(H43,\"Ok.\",\"FAILED!!\")"},read_from_excel_data(Config,{"Sheet1",42,8})]),
  test_util:expected2(read_from_excel_data(Config,{"Sheet1",42,8}), {formula,"=IF(H43,\"Ok.\",\"FAILED!!\")"}).
  
all() -> 
    [sheet1_a16_test,
   sheet1_a27_test,
   sheet1_a38_test,
   sheet1_a22_test,
   sheet1_a33_test,
   sheet1_a44_test,
   sheet1_a28_test,
   sheet1_a39_test,
   sheet1_a1_test,
   sheet1_a12_test,
   sheet1_a34_test,
   sheet1_a7_test,
   sheet1_a18_test,
   sheet1_a29_test,
   sheet1_a40_test,
   sheet1_a13_test,
   sheet1_a35_test,
   sheet1_a8_test,
   sheet1_a19_test,
   sheet1_a30_test,
   sheet1_a41_test,
   sheet1_a3_test,
   sheet1_a14_test,
   sheet1_a25_test,
   sheet1_a36_test,
   sheet1_a20_test,
   sheet1_a31_test,
   sheet1_a42_test,
   sheet1_a4_test,
   sheet1_a26_test,
   sheet1_a37_test,
   sheet1_a10_test,
   sheet1_a21_test,
   sheet1_a32_test,
   sheet1_a43_test,
   sheet1_b27_test,
   sheet1_b38_test,
   sheet1_b33_test,
   sheet1_b28_test,
   sheet1_b39_test,
   sheet1_b12_test,
   sheet1_b34_test,
   sheet1_b7_test,
   sheet1_b29_test,
   sheet1_b40_test,
   sheet1_b13_test,
   sheet1_b35_test,
   sheet1_b8_test,
   sheet1_b30_test,
   sheet1_b41_test,
   sheet1_b25_test,
   sheet1_b36_test,
   sheet1_b31_test,
   sheet1_b42_test,
   sheet1_b26_test,
   sheet1_b37_test,
   sheet1_b32_test,
   sheet1_b43_test,
   sheet1_c27_test,
   sheet1_c38_test,
   sheet1_c33_test,
   sheet1_c28_test,
   sheet1_c39_test,
   sheet1_c34_test,
   sheet1_c29_test,
   sheet1_c40_test,
   sheet1_c35_test,
   sheet1_c30_test,
   sheet1_c41_test,
   sheet1_c25_test,
   sheet1_c36_test,
   sheet1_c31_test,
   sheet1_c42_test,
   sheet1_c26_test,
   sheet1_c37_test,
   sheet1_c32_test,
   sheet1_c43_test,
   sheet1_d27_test,
   sheet1_d38_test,
   sheet1_d33_test,
   sheet1_d28_test,
   sheet1_d39_test,
   sheet1_d34_test,
   sheet1_d29_test,
   sheet1_d40_test,
   sheet1_d35_test,
   sheet1_d30_test,
   sheet1_d41_test,
   sheet1_d25_test,
   sheet1_d36_test,
   sheet1_d31_test,
   sheet1_d42_test,
   sheet1_d26_test,
   sheet1_d37_test,
   sheet1_d32_test,
   sheet1_d43_test,
   sheet1_e27_test,
   sheet1_e38_test,
   sheet1_e33_test,
   sheet1_e28_test,
   sheet1_e39_test,
   sheet1_e34_test,
   sheet1_e29_test,
   sheet1_e40_test,
   sheet1_e35_test,
   sheet1_e30_test,
   sheet1_e41_test,
   sheet1_e25_test,
   sheet1_e36_test,
   sheet1_e31_test,
   sheet1_e42_test,
   sheet1_e26_test,
   sheet1_e37_test,
   sheet1_e32_test,
   sheet1_e43_test,
   sheet1_f27_test,
   sheet1_f38_test,
   sheet1_f33_test,
   sheet1_f28_test,
   sheet1_f39_test,
   sheet1_f34_test,
   sheet1_f29_test,
   sheet1_f40_test,
   sheet1_f35_test,
   sheet1_f30_test,
   sheet1_f41_test,
   sheet1_f25_test,
   sheet1_f36_test,
   sheet1_f31_test,
   sheet1_f42_test,
   sheet1_f26_test,
   sheet1_f37_test,
   sheet1_f32_test,
   sheet1_f43_test,
   sheet1_g27_test,
   sheet1_g38_test,
   sheet1_g33_test,
   sheet1_g28_test,
   sheet1_g39_test,
   sheet1_g34_test,
   sheet1_g29_test,
   sheet1_g40_test,
   sheet1_g35_test,
   sheet1_g30_test,
   sheet1_g41_test,
   sheet1_g25_test,
   sheet1_g36_test,
   sheet1_g31_test,
   sheet1_g42_test,
   sheet1_g26_test,
   sheet1_g37_test,
   sheet1_g32_test,
   sheet1_g43_test,
   sheet1_h27_test,
   sheet1_h38_test,
   sheet1_h33_test,
   sheet1_h28_test,
   sheet1_h39_test,
   sheet1_h34_test,
   sheet1_h29_test,
   sheet1_h40_test,
   sheet1_h35_test,
   sheet1_h30_test,
   sheet1_h41_test,
   sheet1_h25_test,
   sheet1_h36_test,
   sheet1_h31_test,
   sheet1_h42_test,
   sheet1_h26_test,
   sheet1_h37_test,
   sheet1_h32_test,
   sheet1_h43_test,
   sheet1_i27_test,
   sheet1_i38_test,
   sheet1_i33_test,
   sheet1_i28_test,
   sheet1_i39_test,
   sheet1_i34_test,
   sheet1_i29_test,
   sheet1_i40_test,
   sheet1_i35_test,
   sheet1_i30_test,
   sheet1_i41_test,
   sheet1_i25_test,
   sheet1_i36_test,
   sheet1_i31_test,
   sheet1_i42_test,
   sheet1_i26_test,
   sheet1_i37_test,
   sheet1_i32_test,
   sheet1_i43_test
    ].
  
