{application, engine,
	[{description,  "The engine application"},
	 {vsn,          "1.0"},
	 {modules,      [dirty_srv,
			 engine,
			 engine_sup,
			 show,
			 spriki,
			 spriki_funs,
			 userdef,
			 user]},
	 {registered,   [ ]},
	 {included_applications, []},
	 {applications, [kernel, stdlib, mnesia]},
	 {mod,		{engine, [ ]}}]}.
